--Funcion que retorna 1 si el usuario existe y 0 si no existe
CREATE OR REPLACE FUNCTION EXISTE_USUARIO_FN(
    P_CORREO     IN FIDE_USUARIOS_TB.USUARIO_CORREO%TYPE,
    P_CONTRASENNA IN FIDE_USUARIOS_TB.USUARIO_CONTRASENNA%TYPE
) RETURN NUMBER IS
    V_EXISTE NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO V_EXISTE
    FROM FIDE_USUARIOS_TB
    WHERE USUARIO_CORREO = P_CORREO
      AND USUARIO_CONTRASENNA = P_CONTRASENNA;
    IF V_EXISTE > 0 THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;
/
-- Extraer direccion completa usuario por cedula
CREATE OR REPLACE FUNCTION OBTENER_DIRECCION_USUARIO_FN (P_CEDULA_USUARIO VARCHAR2) 
  RETURN VARCHAR2 IS
  V_DIRECCION_SENNAS VARCHAR2(200);
  V_PROVINCIA VARCHAR2(100);
  V_CANTON VARCHAR2(100);
  V_DISTRITO VARCHAR2(100);
BEGIN
  BEGIN
    SELECT D.DIRECCION_SENNAS, P.NOMBRE_PROVINCIA, C.NOMBRE_CANTON, DIS.NOMBRE_DISTRITO
    INTO V_DIRECCION_SENNAS, V_PROVINCIA, V_CANTON, V_DISTRITO
    FROM FIDE_USUARIOS_TB U
    JOIN FIDE_DIRECCION_TB D ON U.ID_DIRECCION_FK = D.ID_DIRECCION_PK
    JOIN FIDE_DIRECCION_PROVINCIA_TB P ON D.ID_DIRECCION_PROVINCIA_FK = P.ID_DIRECCION_PROVINCIA_PK
    JOIN FIDE_DIRECCION_CANTON_TB C ON D.ID_DIRECCION_CANTON_FK = C.ID_DIRECCION_CANTON_PK
    JOIN FIDE_DIRECCION_DISTRITO_TB DIS ON D.ID_DIRECCION_DISTRITO_FK = DIS.ID_DIRECCION_DISTRITO_PK
    WHERE U.USUARIO_IDENTIFICACION = P_CEDULA_USUARIO;
    RETURN V_DIRECCION_SENNAS || ', ' || V_DISTRITO || ', ' || V_CANTON || ', ' || V_PROVINCIA;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN 'NO SE ENCONTRARON REGISTROS CON EL ID ' || P_CEDULA_USUARIO;
  END;
END;
/
-- Extraer mascotas de usuario por cedula
CREATE OR REPLACE FUNCTION OBTENER_MASCOTAS_USUARIO_FN (P_IDENTIFICACION_USUARIO VARCHAR2) 
  RETURN VARCHAR2 IS
  V_NOMBRE_MASCOTA VARCHAR2(100);
  V_RESULTADO VARCHAR2(4000);
BEGIN
  V_RESULTADO := '';
  FOR M IN (
        SELECT M.NOMBRE_MASCOTA
        FROM FIDE_MASCOTA_TB M
        JOIN FIDE_USUARIOS_TB U ON M.ID_USUARIO_FK = U.ID_USUARIO_PK
        WHERE U.USUARIO_IDENTIFICACION = P_IDENTIFICACION_USUARIO) 
  LOOP
    V_RESULTADO := V_RESULTADO || M.NOMBRE_MASCOTA || ', ';
  END LOOP;

  IF V_RESULTADO IS NULL OR V_RESULTADO = '' THEN
    RETURN 'NO SE ENCONTRARON MASCOTAS PARA EL USUARIO ' || P_IDENTIFICACION_USUARIO;
  ELSE
    RETURN RTRIM(V_RESULTADO, ', ');
  END IF;
END;
/
--Funcion que retorna 1 si la raza existe y 0 si no existe
CREATE OR REPLACE FUNCTION EXISTE_RAZA_POR_DESCRIPCION_FN(
  P_NOMBRE_RAZA VARCHAR2
) RETURN NUMBER IS
  V_COUNT NUMBER; 
BEGIN 
  SELECT COUNT(*) INTO V_COUNT
  FROM FIDE_MASCOTA_RAZA_TB 
  WHERE NOMBRE_RAZA = P_NOMBRE_RAZA;

  IF V_COUNT > 0 THEN 
    RETURN 1;
  ELSE 
    RETURN 0;
  END IF; 
END;
/
--Validar fecha de cirugia por ID
CREATE OR REPLACE FUNCTION OBTENER_FECHA_CIRUGIA_FN(
  P_ID_CIRUGIA NUMBER
) 
RETURN DATE IS 
  V_FECHA DATE; 
BEGIN 
  SELECT CIRUGIA_FECHA_INICIO 
  INTO V_FECHA 
  FROM FIDE_REGISTRO_CIRUGIAS_TB 
  WHERE ID_CIRUGIA_PK = P_ID_CIRUGIA; 
  RETURN V_FECHA; 
EXCEPTION 
  WHEN NO_DATA_FOUND THEN 
    RETURN NULL;
  WHEN OTHERS THEN 
    RETURN NULL;
END;
/
-- Obtener duenno mascota
CREATE OR REPLACE FUNCTION OBTENER_DUENNO_MASCOTA_FN (P_ID_MASCOTA NUMBER) 
  RETURN NUMBER IS
  V_NOMBRE_DUENNO VARCHAR2(100);
  V_RESULTADO VARCHAR2(100);
BEGIN
  V_RESULTADO := '';
  FOR M IN (
        SELECT U.USUARIO_NOMBRE
        FROM FIDE_USUARIOS_TB U
        JOIN FIDE_MASCOTA_TB M ON M.ID_USUARIO_FK = U.ID_USUARIO_PK
        WHERE M.ID_MASCOTA_PK = P_ID_MASCOTA) 
  LOOP
    V_RESULTADO := V_RESULTADO || U.USUARIO_NOMBRE || ', ';
  END LOOP;

  IF V_RESULTADO IS NULL OR V_RESULTADO = '' THEN
    RETURN 'NO SE ENCONTRARON MASCOTAS PARA EL USUARIO ' || P_IDENTIFICACION_USUARIO;
  ELSE
    RETURN RTRIM(V_RESULTADO, ', ');
  END IF;
END;
/
-- Obtener nombre por ID
CREATE OR REPLACE FUNCTION OBTENER_USUARIO_POR_ID_FN(P_ID NUMBER)
    RETURN VARCHAR2 IS
    V_NOMBRE_USUARIO VARCHAR2(200);
BEGIN 
    SELECT USUARIO_NOMBRE INTO V_NOMBRE_USUARIO
    FROM FIDE_USUARIOS_TB 
    WHERE ID_USUARIO_PK = P_ID;
    RETURN V_NOMBRE_USUARIO;
EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        RETURN 'NO SE ENCONTRÓ EL USUARIO CON ID ' || P_ID;
    WHEN OTHERS THEN 
        RETURN 'ERROR AL OBTENER EL USUARIO';
END;
/



select OBTENER_USUARIO_POR_ID_FN(1) from dual;



