--Funcion que retorna 1 si el usuario existe y 0 si no existe
CREATE OR REPLACE FUNCTION EXISTE_USUARIO_FN(
    P_CORREO     IN FIDE_USUARIOS_TB.USUARIO_CORREO%TYPE,
    P_CONTRASENNA IN FIDE_USUARIOS_TB.USUARIO_CONTRASENNA%TYPE
) RETURN NUMBER IS
    CURSOR C_EXISTE IS
        SELECT 1
        FROM FIDE_USUARIOS_TB
        WHERE USUARIO_CORREO = P_CORREO
          AND USUARIO_CONTRASENNA = P_CONTRASENNA;

    V_EXISTE NUMBER := 0;
BEGIN
    FOR REC IN C_EXISTE LOOP
        V_EXISTE := 1;
    END LOOP;

    RETURN V_EXISTE;
END EXISTE_USUARIO_FN;
/
-- Extraer direccion completa usuario por cedula
CREATE OR REPLACE FUNCTION OBTENER_DIRECCION_USUARIO_FN (P_CEDULA_USUARIO VARCHAR2)
  RETURN VARCHAR2 IS
  CURSOR C_DIRECCION IS
                                        SELECT D.DIRECCION_SENNAS, P.NOMBRE_PROVINCIA, C.NOMBRE_CANTON, DIS.NOMBRE_DISTRITO
                                        FROM FIDE_USUARIOS_TB U
                                        JOIN FIDE_DIRECCION_TB D ON U.ID_DIRECCION_FK = D.ID_DIRECCION_PK
                                        JOIN FIDE_DIRECCION_PROVINCIA_TB P ON D.ID_DIRECCION_PROVINCIA_FK = P.ID_DIRECCION_PROVINCIA_PK
                                        JOIN FIDE_DIRECCION_CANTON_TB C ON D.ID_DIRECCION_CANTON_FK = C.ID_DIRECCION_CANTON_PK
                                        JOIN FIDE_DIRECCION_DISTRITO_TB DIS ON D.ID_DIRECCION_DISTRITO_FK = DIS.ID_DIRECCION_DISTRITO_PK
                                        WHERE U.USUARIO_IDENTIFICACION = P_CEDULA_USUARIO;
  V_DIRECCION VARCHAR2(4000);
BEGIN
  FOR REC IN C_DIRECCION LOOP
    V_DIRECCION := REC.DIRECCION_SENNAS || ', ' || REC.NOMBRE_DISTRITO || ', ' || REC.NOMBRE_CANTON || ', ' || REC.NOMBRE_PROVINCIA;
  END LOOP;
  RETURN V_DIRECCION;
END;
/
-- Extraer mascotas de usuario por cedula
CREATE OR REPLACE FUNCTION OBTENER_MASCOTAS_USUARIO_FN (
    P_IDENTIFICACION_USUARIO VARCHAR2
) RETURN VARCHAR2 IS

    CURSOR C_MASCOTAS IS
        SELECT M.NOMBRE_MASCOTA
        FROM FIDE_MASCOTA_TB M
        JOIN FIDE_USUARIOS_TB U ON M.ID_USUARIO_FK = U.ID_USUARIO_PK
        WHERE U.USUARIO_IDENTIFICACION = P_IDENTIFICACION_USUARIO;
        
    V_RESULTADO VARCHAR2(4000) := '';
BEGIN
    FOR REC IN C_MASCOTAS LOOP
        V_RESULTADO := V_RESULTADO || REC.NOMBRE_MASCOTA || ', ';
    END LOOP;

    IF V_RESULTADO IS NULL OR V_RESULTADO = '' THEN
        RETURN 'NO SE ENCONTRARON MASCOTAS PARA EL USUARIO ' || P_IDENTIFICACION_USUARIO;
    ELSE
        RETURN V_RESULTADO; 
    END IF;
END OBTENER_MASCOTAS_USUARIO_FN;
/
--Funcion que retorna 1 si la raza existe y 0 si no existe
CREATE OR REPLACE FUNCTION EXISTE_RAZA_POR_DESCRIPCION_FN(
  P_NOMBRE_RAZA VARCHAR2
) RETURN NUMBER IS
  CURSOR C_EXISTE IS 
  SELECT 1 
  FROM FIDE_MASCOTA_RAZA_TB 
  WHERE NOMBRE_RAZA = P_NOMBRE_RAZA;
    
    V_EXISTE NUMBER :=0;
    BEGIN
    FOR REC IN C_EXISTE LOOP
        V_EXISTE :=1;
    END LOOP;
   
   RETURN V_EXISTE;
END EXISTE_RAZA_POR_DESCRIPCION_FN;
/
--Validar fecha de cirugia por ID
CREATE OR REPLACE FUNCTION OBTENER_FECHA_CIRUGIA_FN(
  P_ID_CIRUGIA NUMBER
) 
RETURN DATE IS
    CURSOR C_FECHA IS
  SELECT CIRUGIA_FECHA_INICIO 
  FROM FIDE_REGISTRO_CIRUGIAS_TB 
  WHERE ID_CIRUGIA_PK = P_ID_CIRUGIA; 
  V_FECHA DATE;
  BEGIN
  FOR REC IN C_FECHA LOOP
    V_FECHA:= REC.CIRUGIA_FECHA_INICIO;
    END LOOP;
    IF V_FECHA IS NULL THEN
        RETURN 'NO SE ENCONTRÓ FECHA PARA LA CITA';
    ELSE
        RETURN V_FECHA;
    END IF;
 
END OBTENER_FECHA_CIRUGIA_FN;
/
-- Obtener duenno mascota
CREATE OR REPLACE FUNCTION OBTENER_DUENNO_MASCOTA_FN (P_ID_MASCOTA NUMBER) 
  RETURN VARCHAR2 IS
  CURSOR C_DUENNO IS
    SELECT U.USUARIO_NOMBRE
    FROM FIDE_USUARIOS_TB U
    JOIN FIDE_MASCOTA_TB M ON M.ID_USUARIO_FK = U.ID_USUARIO_PK
    WHERE M.ID_MASCOTA_PK = P_ID_MASCOTA;
    
    V_RESULTADO VARCHAR2(4000):='';
  BEGIN
      FOR REC IN C_DUENNO LOOP
        V_RESULTADO := V_RESULTADO || REC.USUARIO_NOMBRE || ', ';
      END LOOP;
    
      IF V_RESULTADO IS NULL OR V_RESULTADO = '' THEN
        RETURN 'NO SE ENCONTRÓ DUEÑO PARA LA MASCOTA CON ID ' || P_ID_MASCOTA;
      ELSE
        RETURN RTRIM(V_RESULTADO, ', ');
      END IF;
  END OBTENER_DUENNO_MASCOTA_FN;
/
-- Obtener nombre por ID
CREATE OR REPLACE FUNCTION OBTENER_USUARIO_POR_ID_FN(P_ID NUMBER)
    RETURN VARCHAR2 IS
    CURSOR C_NOMBRE IS
        SELECT USUARIO_NOMBRE
        FROM FIDE_USUARIOS_TB 
        WHERE ID_USUARIO_PK = P_ID;
    
    V_NOMBRE VARCHAR2(4000) := '';
BEGIN
   
    FOR REC IN C_NOMBRE LOOP
        V_NOMBRE := REC.USUARIO_NOMBRE; 
    END LOOP;
    
    IF V_NOMBRE IS NULL OR V_NOMBRE = '' THEN
        RETURN 'NO SE ENCONTRÓ NOMBRE DEL USUARIO CON EL ID ' || P_ID;
    ELSE
        RETURN V_NOMBRE;
    END IF;
END OBTENER_USUARIO_POR_ID_FN;
/

