--Creacion procedimiento de inserciones FIDE_ESTADO_TB
CREATE OR REPLACE PROCEDURE INSERT_ESTADO_TB_SP(
                                            P_ID_ESTADO IN FIDE_ESTADO_TB.ID_ESTADO_PK%TYPE,
                                            P_ESTADO_DESCRIPCION IN FIDE_ESTADO_TB.ESTADO_DESCRIPCION%TYPE,
                                            P_CREATED_BY IN FIDE_ESTADO_TB.CREATED_BY%TYPE,
                                            P_CREATION_DATE IN FIDE_ESTADO_TB.CREATION_DATE%TYPE,
                                            P_MODIFIED_BY IN FIDE_ESTADO_TB.MODIFIED_BY%TYPE,
                                            P_MODIFICATION_DATE IN FIDE_ESTADO_TB.MODIFICATION_DATE%TYPE
    )
    IS
    BEGIN 
    INSERT INTO FIDE_ESTADO_TB(ID_ESTADO_PK, ESTADO_DESCRIPCION,CREATED_BY,CREATION_DATE, MODIFIED_BY,MODIFICATION_DATE)
    VALUES(P_ID_ESTADO, P_ESTADO_DESCRIPCION, P_CREATED_BY, P_CREATION_DATE, P_MODIFIED_BY, P_MODIFICATION_DATE);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DATOS INGRESADOS CON EXITO');
    EXCEPTION
            WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON REGISTROS PARA INSERTAR');
            WHEN OTHERS THEN
                    DBMS_OUTPUT.PUT_LINE('ERROR COMUNIQUESE CON TI '|| SQLERRM);
    END;
/
--Creacion procedimiento de inserciones FIDE_DIRECCION_PROVINCIA_TB
CREATE OR REPLACE PROCEDURE INSERT_DIRECCION_PROVINCIA_TB_SP(
                                            P_ID_DIRECCION_PROVINCIA IN FIDE_DIRECCION_PROVINCIA_TB.ID_DIRECCION_PROVINCIA_PK%TYPE,
                                            P_ESTADO IN FIDE_DIRECCION_PROVINCIA_TB.ID_ESTADO_FK%TYPE,
                                            P_NOMBRE_PROVINCIA IN FIDE_DIRECCION_PROVINCIA_TB.NOMBRE_PROVINCIA%TYPE,
                                            P_CREATED_BY IN FIDE_DIRECCION_PROVINCIA_TB.CREATED_BY%TYPE,
                                            P_CREATION_DATE IN FIDE_DIRECCION_PROVINCIA_TB.CREATION_DATE%TYPE,
                                            P_MODIFIED_BY IN FIDE_DIRECCION_PROVINCIA_TB.MODIFIED_BY%TYPE,
                                            P_MODIFICATION_DATE IN FIDE_DIRECCION_PROVINCIA_TB.MODIFICATION_DATE%TYPE
    )
    IS
    BEGIN 
    INSERT INTO FIDE_DIRECCION_PROVINCIA_TB(ID_DIRECCION_PROVINCIA_PK, ID_ESTADO_FK, NOMBRE_PROVINCIA,CREATED_BY,CREATION_DATE, MODIFIED_BY,MODIFICATION_DATE)
    VALUES(P_ID_DIRECCION_PROVINCIA, P_ESTADO, P_NOMBRE_PROVINCIA, P_CREATED_BY, P_CREATION_DATE, P_MODIFIED_BY, P_MODIFICATION_DATE);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DATOS INGRESADOS CON EXITO');
    EXCEPTION
            WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON REGISTROS PARA INSERTAR');
            WHEN OTHERS THEN
                    DBMS_OUTPUT.PUT_LINE('ERROR COMUNIQUESE CON TI '|| SQLERRM);
    END;
/
--Creacion procedimiento de inserciones FIDE_DIRECCION_CANTON_TB
CREATE OR REPLACE PROCEDURE INSERT_DIRECCION_CANTON_TB_SP(
                                            P_ID_DIRECCION_CANTON IN FIDE_DIRECCION_CANTON_TB.ID_DIRECCION_CANTON_PK%TYPE,
                                            P_ESTADO IN FIDE_DIRECCION_CANTON_TB.ID_ESTADO_FK%TYPE,
                                            P_NOMBRE_CANTON IN FIDE_DIRECCION_CANTON_TB.NOMBRE_CANTON%TYPE,
                                            P_CREATED_BY IN FIDE_DIRECCION_CANTON_TB.CREATED_BY%TYPE,
                                            P_CREATION_DATE IN FIDE_DIRECCION_CANTON_TB.CREATION_DATE%TYPE,
                                            P_MODIFIED_BY IN FIDE_DIRECCION_CANTON_TB.MODIFIED_BY%TYPE,
                                            P_MODIFICATION_DATE IN FIDE_DIRECCION_CANTON_TB.MODIFICATION_DATE%TYPE
    )
    IS
    BEGIN 
    INSERT INTO FIDE_DIRECCION_CANTON_TB(ID_DIRECCION_CANTON_PK, ID_ESTADO_FK, NOMBRE_CANTON,CREATED_BY,CREATION_DATE, MODIFIED_BY,MODIFICATION_DATE)
    VALUES(P_ID_DIRECCION_CANTON, P_ESTADO, P_NOMBRE_CANTON, P_CREATED_BY, P_CREATION_DATE, P_MODIFIED_BY, P_MODIFICATION_DATE);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DATOS INGRESADOS CON EXITO');
    EXCEPTION
            WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON REGISTROS PARA INSERTAR');
            WHEN OTHERS THEN
                    DBMS_OUTPUT.PUT_LINE('ERROR COMUNIQUESE CON TI '|| SQLERRM);
    END;
/
--Creacion procedimiento de inserciones FIDE_DIRECCION_DISTRITO_TB
CREATE OR REPLACE PROCEDURE INSERT_DIRECCION_DISTRITO_TB_SP(
                                            P_ID_DIRECCION_DISTRITO IN FIDE_DIRECCION_DISTRITO_TB.ID_DIRECCION_DISTRITO_PK%TYPE,
                                            P_ESTADO IN FIDE_DIRECCION_DISTRITO_TB.ID_ESTADO_FK%TYPE,
                                            P_NOMBRE_DISTRITO IN FIDE_DIRECCION_DISTRITO_TB.NOMBRE_DISTRITO%TYPE,
                                            P_CREATED_BY IN FIDE_DIRECCION_DISTRITO_TB.CREATED_BY%TYPE,
                                            P_CREATION_DATE IN FIDE_DIRECCION_DISTRITO_TB.CREATION_DATE%TYPE,
                                            P_MODIFIED_BY IN FIDE_DIRECCION_DISTRITO_TB.MODIFIED_BY%TYPE,
                                            P_MODIFICATION_DATE IN FIDE_DIRECCION_DISTRITO_TB.MODIFICATION_DATE%TYPE
    )
    IS
    BEGIN 
    INSERT INTO FIDE_DIRECCION_DISTRITO_TB(ID_DIRECCION_DISTRITO_PK, ID_ESTADO_FK, NOMBRE_DISTRITO,CREATED_BY,CREATION_DATE, MODIFIED_BY,MODIFICATION_DATE)
    VALUES(P_ID_DIRECCION_DISTRITO, P_ESTADO, P_NOMBRE_DISTRITO, P_CREATED_BY, P_CREATION_DATE, P_MODIFIED_BY, P_MODIFICATION_DATE);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DATOS INGRESADOS CON EXITO');
    EXCEPTION
            WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON REGISTROS PARA INSERTAR');
            WHEN OTHERS THEN
                    DBMS_OUTPUT.PUT_LINE('ERROR COMUNIQUESE CON TI '|| SQLERRM);
    END;
/
--Creacion procedimiento de inserciones FIDE_DIRECCION_TB
CREATE OR REPLACE PROCEDURE INSERT_DIRECCION_TB_SP(
                                            P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION_PK%TYPE,
                                            P_ESTADO IN FIDE_DIRECCION_TB.ID_ESTADO_FK%TYPE,
                                            P_DIRECCION_PROVINCIA IN FIDE_DIRECCION_TB.ID_DIRECCION_PROVINCIA_FK%TYPE,
                                            P_DIRECCION_CANTON IN FIDE_DIRECCION_TB.ID_DIRECCION_CANTON_FK%TYPE,
                                            P_DIRECCION_DISTRITO IN FIDE_DIRECCION_TB.ID_DIRECCION_DISTRITO_FK%TYPE,
                                            P_DIRECCION_SENNAS IN FIDE_DIRECCION_TB.DIRECCION_SENNAS%TYPE,
                                            P_CREATED_BY IN FIDE_DIRECCION_TB.CREATED_BY%TYPE,
                                            P_CREATION_DATE IN FIDE_DIRECCION_TB.CREATION_DATE%TYPE,
                                            P_MODIFIED_BY IN FIDE_DIRECCION_TB.MODIFIED_BY%TYPE,
                                            P_MODIFICATION_DATE IN FIDE_DIRECCION_TB.MODIFICATION_DATE%TYPE
    )
    IS
    BEGIN 
    INSERT INTO FIDE_DIRECCION_TB(ID_DIRECCION_PK, ID_ESTADO_FK, ID_DIRECCION_PROVINCIA_FK, ID_DIRECCION_CANTON_FK, ID_DIRECCION_DISTRITO_FK, DIRECCION_SENNAS,
                                    CREATED_BY,CREATION_DATE, MODIFIED_BY,MODIFICATION_DATE)
    VALUES(P_ID_DIRECCION, P_ESTADO, P_DIRECCION_PROVINCIA, P_DIRECCION_CANTON, P_DIRECCION_DISTRITO, P_DIRECCION_SENNAS,
            P_CREATED_BY, P_CREATION_DATE, P_MODIFIED_BY, P_MODIFICATION_DATE);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DATOS INGRESADOS CON EXITO');
    EXCEPTION
            WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON REGISTROS PARA INSERTAR');
            WHEN OTHERS THEN
                    DBMS_OUTPUT.PUT_LINE('ERROR COMUNIQUESE CON TI '|| SQLERRM);
    END;
/
--Creacion procedimiento de inserciones FIDE_TELEFONO_CONTACTO_TB
CREATE OR REPLACE PROCEDURE INSERT_TELEFONO_CONTACTO_TB_SP(
                                            P_ID_TELEFONO_CONTACTO IN FIDE_TELEFONO_CONTACTO_TB.ID_TELEFONO_CONTACTO_PK%TYPE,
                                            P_ESTADO IN FIDE_TELEFONO_CONTACTO_TB.ID_ESTADO_FK%TYPE,
                                            P_TELEFONO_CONTACTO IN FIDE_TELEFONO_CONTACTO_TB.TELEFONO_CONTACTO%TYPE,
                                            P_CREATED_BY IN FIDE_TELEFONO_CONTACTO_TB.CREATED_BY%TYPE,
                                            P_CREATION_DATE IN FIDE_TELEFONO_CONTACTO_TB.CREATION_DATE%TYPE,
                                            P_MODIFIED_BY IN FIDE_TELEFONO_CONTACTO_TB.MODIFIED_BY%TYPE,
                                            P_MODIFICATION_DATE IN FIDE_TELEFONO_CONTACTO_TB.MODIFICATION_DATE%TYPE
    )
    IS
    BEGIN 
    INSERT INTO FIDE_TELEFONO_CONTACTO_TB(ID_TELEFONO_CONTACTO_PK, ID_ESTADO_FK, TELEFONO_CONTACTO,CREATED_BY,CREATION_DATE, MODIFIED_BY,MODIFICATION_DATE)
    VALUES(P_ID_TELEFONO_CONTACTO, P_ESTADO, P_TELEFONO_CONTACTO, P_CREATED_BY, P_CREATION_DATE, P_MODIFIED_BY, P_MODIFICATION_DATE);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DATOS INGRESADOS CON EXITO');
    EXCEPTION
            WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON REGISTROS PARA INSERTAR');
            WHEN OTHERS THEN
                    DBMS_OUTPUT.PUT_LINE('ERROR COMUNIQUESE CON TI '|| SQLERRM);
    END;
/
--Creacion procedimiento de inserciones FIDE_TIPO_USUARIO_TB
CREATE OR REPLACE PROCEDURE INSERT_TIPO_USUARIO_TB_SP(
                                            P_ID_TIPO_USUARIO IN FIDE_TIPO_USUARIO_TB.ID_TIPO_USUARIO_PK%TYPE,
                                            P_ESTADO IN FIDE_TIPO_USUARIO_TB.ID_ESTADO_FK%TYPE,
                                            P_DESCRIPCION_TIPO_USUARIO IN FIDE_TIPO_USUARIO_TB.DESCRIPCION_TIPO_USUARIO%TYPE,
                                            P_CREATED_BY IN FIDE_TIPO_USUARIO_TB.CREATED_BY%TYPE,
                                            P_CREATION_DATE IN FIDE_TIPO_USUARIO_TB.CREATION_DATE%TYPE,
                                            P_MODIFIED_BY IN FIDE_TIPO_USUARIO_TB.MODIFIED_BY%TYPE,
                                            P_MODIFICATION_DATE IN FIDE_TIPO_USUARIO_TB.MODIFICATION_DATE%TYPE
    )
    IS
    BEGIN 
    INSERT INTO FIDE_TIPO_USUARIO_TB(ID_TIPO_USUARIO_PK, ID_ESTADO_FK, DESCRIPCION_TIPO_USUARIO,CREATED_BY,CREATION_DATE, MODIFIED_BY,MODIFICATION_DATE)
    VALUES(P_ID_TIPO_USUARIO, P_ESTADO, P_DESCRIPCION_TIPO_USUARIO, P_CREATED_BY, P_CREATION_DATE, P_MODIFIED_BY, P_MODIFICATION_DATE);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DATOS INGRESADOS CON EXITO');
    EXCEPTION
            WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON REGISTROS PARA INSERTAR');
            WHEN OTHERS THEN
                    DBMS_OUTPUT.PUT_LINE('ERROR COMUNIQUESE CON TI '|| SQLERRM);
    END;
/
--Creacion procedimiento de inserciones FIDE_TIPO_USUARIO_TB
CREATE OR REPLACE PROCEDURE INSERT_TIPO_USUARIO_TB_SP(
                                            P_ID_TIPO_USUARIO IN FIDE_TIPO_USUARIO_TB.ID_TIPO_USUARIO_PK%TYPE,
                                            P_ESTADO IN FIDE_TIPO_USUARIO_TB.ID_ESTADO_FK%TYPE,
                                            P_DESCRIPCION_TIPO_USUARIO IN FIDE_TIPO_USUARIO_TB.DESCRIPCION_TIPO_USUARIO%TYPE,
                                            P_CREATED_BY IN FIDE_TIPO_USUARIO_TB.CREATED_BY%TYPE,
                                            P_CREATION_DATE IN FIDE_TIPO_USUARIO_TB.CREATION_DATE%TYPE,
                                            P_MODIFIED_BY IN FIDE_TIPO_USUARIO_TB.MODIFIED_BY%TYPE,
                                            P_MODIFICATION_DATE IN FIDE_TIPO_USUARIO_TB.MODIFICATION_DATE%TYPE
    )
    IS
    BEGIN 
    INSERT INTO FIDE_TIPO_USUARIO_TB(ID_TIPO_USUARIO_PK, ID_ESTADO_FK, DESCRIPCION_TIPO_USUARIO,CREATED_BY,CREATION_DATE, MODIFIED_BY,MODIFICATION_DATE)
    VALUES(P_ID_TIPO_USUARIO, P_ESTADO, P_DESCRIPCION_TIPO_USUARIO, P_CREATED_BY, P_CREATION_DATE, P_MODIFIED_BY, P_MODIFICATION_DATE);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DATOS INGRESADOS CON EXITO');
    EXCEPTION
            WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON REGISTROS PARA INSERTAR');
            WHEN OTHERS THEN
                    DBMS_OUTPUT.PUT_LINE('ERROR COMUNIQUESE CON TI '|| SQLERRM);
    END;
/
--Creacion procedimiento de inserciones FIDE_ESPECIALIDAD_TB
CREATE OR REPLACE PROCEDURE INSERT_ESPECIALIDAD_TB_SP(
                                            P_ID_ESPECIALIDAD IN FIDE_ESPECIALIDAD_TB.ID_ESPECIALIDAD_PK%TYPE,
                                            P_ESTADO IN FIDE_ESPECIALIDAD_TB.ID_ESTADO_FK%TYPE,
                                            P_NOMBRE_ESPECIALIDAD IN FIDE_ESPECIALIDAD_TB.NOMBRE_ESPECIALIDAD%TYPE,
                                            P_DESCRIPCION_ESPECIALIDAD IN FIDE_ESPECIALIDAD_TB.DESCRIPCION_ESPECIALIDAD%TYPE,
                                            P_CREATED_BY IN FIDE_ESPECIALIDAD_TB.CREATED_BY%TYPE,
                                            P_CREATION_DATE IN FIDE_ESPECIALIDAD_TB.CREATION_DATE%TYPE,
                                            P_MODIFIED_BY IN FIDE_ESPECIALIDAD_TB.MODIFIED_BY%TYPE,
                                            P_MODIFICATION_DATE IN FIDE_ESPECIALIDAD_TB.MODIFICATION_DATE%TYPE
    )
    IS
    BEGIN 
    INSERT INTO FIDE_ESPECIALIDAD_TB(ID_ESPECIALIDAD_PK, ID_ESTADO_FK, NOMBRE_ESPECIALIDAD, DESCRIPCION_ESPECIALIDAD,CREATED_BY,CREATION_DATE, MODIFIED_BY,MODIFICATION_DATE)
    VALUES(P_ID_ESPECIALIDAD, P_ESTADO, P_NOMBRE_ESPECIALIDAD, P_DESCRIPCION_ESPECIALIDAD, P_CREATED_BY, P_CREATION_DATE, P_MODIFIED_BY, P_MODIFICATION_DATE);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DATOS INGRESADOS CON EXITO');
    EXCEPTION
            WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON REGISTROS PARA INSERTAR');
            WHEN OTHERS THEN
                    DBMS_OUTPUT.PUT_LINE('ERROR COMUNIQUESE CON TI '|| SQLERRM);
    END;
/
--Creacion procedimiento de inserciones FIDE_USUARIOS_TB
CREATE OR REPLACE PROCEDURE INSERT_USUARIOS_TB_SP(
                                            P_ID_USUARIO IN FIDE_USUARIOS_TB.ID_USUARIO_PK%TYPE,
                                            P_ESTADO IN FIDE_USUARIOS_TB.ID_ESTADO_FK%TYPE,
                                            P_ESPECIALIDAD IN FIDE_USUARIOS_TB.ID_ESPECIALIDAD_FK%TYPE,
                                            P_ID_TIPO_USUARIO IN FIDE_USUARIOS_TB.ID_TIPO_USUARIO_FK%TYPE,
                                            P_USUARIO_NOMBRE IN FIDE_USUARIOS_TB.USUARIO_NOMBRE%TYPE,
                                            P_USUARIO_CORREO IN FIDE_USUARIOS_TB.USUARIO_CORREO%TYPE,
                                            P_USUARIO_CONTRASENNA IN FIDE_USUARIOS_TB.USUARIO_CONTRASENNA%TYPE,
                                            P_USUARIO_IDENTIFICACION IN FIDE_USUARIOS_TB.USUARIO_IDENTIFICACION%TYPE,
                                            P_USUARIO_FECHA_REGISTRO IN FIDE_USUARIOS_TB.USUARIO_FECHA_REGISTRO%TYPE,
                                            P_USUARIO_CUENTA_BANCARIAO IN FIDE_USUARIOS_TB.USUARIO_CUENTA_BANCARIA%TYPE,                                            
                                            P_CREATED_BY IN FIDE_USUARIOS_TB.CREATED_BY%TYPE,
                                            P_CREATION_DATE IN FIDE_USUARIOS_TB.CREATION_DATE%TYPE,
                                            P_MODIFIED_BY IN FIDE_USUARIOS_TB.MODIFIED_BY%TYPE,
                                            P_MODIFICATION_DATE IN FIDE_USUARIOS_TB.MODIFICATION_DATE%TYPE
    )
    IS
    BEGIN 
    INSERT INTO FIDE_USUARIOS_TB(ID_USUARIO_PK, ID_ESTADO_FK, ID_ESPECIALIDAD_FK, ID_TIPO_USUARIO_FK, USUARIO_NOMBRE, USUARIO_CORREO, USUARIO_CONTRASENNA, USUARIO_IDENTIFICACION, USUARIO_FECHA_REGISTRO,
                                  USUARIO_CUENTA_BANCARIA, CREATED_BY,CREATION_DATE, MODIFIED_BY,MODIFICATION_DATE)
    VALUES(P_ID_USUARIO, P_ESTADO, P_ESPECIALIDAD, P_ID_TIPO_USUARIO, P_USUARIO_NOMBRE, P_USUARIO_CORREO, P_USUARIO_CONTRASENNA, P_USUARIO_IDENTIFICACION, P_USUARIO_FECHA_REGISTRO, 
        P_USUARIO_CUENTA_BANCARIAO, P_CREATED_BY, P_CREATION_DATE, P_MODIFIED_BY, P_MODIFICATION_DATE);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DATOS INGRESADOS CON EXITO');
    EXCEPTION
            WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON REGISTROS PARA INSERTAR');
            WHEN OTHERS THEN
                    DBMS_OUTPUT.PUT_LINE('ERROR COMUNIQUESE CON TI '|| SQLERRM);
    END;
