/*
Proyecto Final - Grupo 3

Integrantes:
Cordero Ramirez Emmanuel
Sandi Molina Deyber 
Vargas Arias Cristopher
Velazquez Rojas Vivian Michelle
*/

/*------------------------------------------------------------------------------
---------------------------------BASE DE DATOS HUELLITAS------------------------
------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------
---------------------------------CREACION DE TABLAS-----------------------------
------------------------------------------------------------------------------*/

--Creacion tabla FIDE_ESTADO_TB
CREATE TABLE FIDE_ESTADO_TB (
    ID_ESTADO_PK NUMBER NOT NULL,
    ESTADO_DESCRIPCION VARCHAR2(100) NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_ESTADO_PK PRIMARY KEY (ID_ESTADO_PK)
);
/
--Creacion tabla FIDE_DIRECCION_PROVINCIA_TB
CREATE TABLE FIDE_DIRECCION_PROVINCIA_TB (
    ID_DIRECCION_PROVINCIA_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    NOMBRE_PROVINCIA VARCHAR2(100) NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_DIRECCION_PROVINCIA_PK PRIMARY KEY (ID_DIRECCION_PROVINCIA_PK),
    CONSTRAINT FIDE_DIRECCION_PROVINCIA_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
--Creacion tabla FIDE_DIRECCION_CANTON_TB
CREATE TABLE FIDE_DIRECCION_CANTON_TB (
    ID_DIRECCION_CANTON_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    NOMBRE_CANTON VARCHAR2(100) NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_DIRECCION_CANTON_PK PRIMARY KEY (ID_DIRECCION_CANTON_PK),
    CONSTRAINT FIDE_DIRECCION_CANTON_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
--Creacion tabla FIDE_DIRECCION_DISTRITO_TB
CREATE TABLE FIDE_DIRECCION_DISTRITO_TB (
    ID_DIRECCION_DISTRITO_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    NOMBRE_DISTRITO VARCHAR2(100) NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_DIRECCION_DISTRITO_PK PRIMARY KEY (ID_DIRECCION_DISTRITO_PK),
    CONSTRAINT FIDE_DIRECCION_DISTRITO_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
--Creacion tabla FIDE_DIRECCION_TB
CREATE TABLE FIDE_DIRECCION_TB (
    ID_DIRECCION_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    ID_DIRECCION_PROVINCIA_FK NUMBER NOT NULL,
    ID_DIRECCION_CANTON_FK NUMBER NOT NULL,
    ID_DIRECCION_DISTRITO_FK NUMBER NOT NULL,
    DIRECCION_SENNAS VARCHAR2(200),
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_DIRECCION_PK PRIMARY KEY (ID_DIRECCION_PK),
    CONSTRAINT FIDE_DIRECCION_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK),
    CONSTRAINT FIDE_DIRECCION_PROVINCIA_FK FOREIGN KEY (ID_DIRECCION_PROVINCIA_FK) REFERENCES FIDE_DIRECCION_PROVINCIA_TB(ID_DIRECCION_PROVINCIA_PK),
    CONSTRAINT FIDE_DIRECCION_CANTON_FK FOREIGN KEY (ID_DIRECCION_CANTON_FK) REFERENCES FIDE_DIRECCION_CANTON_TB(ID_DIRECCION_CANTON_PK),
    CONSTRAINT FIDE_DIRECCION_DISTRITO_FK FOREIGN KEY (ID_DIRECCION_DISTRITO_FK) REFERENCES FIDE_DIRECCION_DISTRITO_TB(ID_DIRECCION_DISTRITO_PK)
);
/
-- Creacion tabla FIDE_TELEFONO_CONTACTO_TB
CREATE TABLE FIDE_TELEFONO_CONTACTO_TB (
    ID_TELEFONO_CONTACTO_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    TELEFONO_CONTACTO NUMBER NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_TELEFONO_CONTACTO_PK PRIMARY KEY (ID_TELEFONO_CONTACTO_PK),
    CONSTRAINT FIDE_TELEFONO_CONTACTO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_TIPO_USUARIO_TB
CREATE TABLE FIDE_TIPO_USUARIO_TB (
    ID_TIPO_USUARIO_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    DESCRIPCION_TIPO_USUARIO VARCHAR2(100) NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_TIPO_USUARIO_PK PRIMARY KEY (ID_TIPO_USUARIO_PK),
    CONSTRAINT FIDE_TIPO_USUARIO_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_ESPECIALIDAD_TB
CREATE TABLE FIDE_ESPECIALIDAD_TB (
    ID_ESPECIALIDAD_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    NOMBRE_ESPECIALIDAD VARCHAR2(100) NOT NULL,
    DESCRIPCION_ESPECIALIDAD VARCHAR2(200) NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_ESPECIALIDAD_PK PRIMARY KEY (ID_ESPECIALIDAD_PK),
    CONSTRAINT FIDE_ESPECIALIDAD_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_USUARIOS_TB
CREATE TABLE FIDE_USUARIOS_TB (
    ID_USUARIO_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    ID_ESPECIALIDAD_FK NUMBER,
    ID_TIPO_USUARIO_FK NUMBER NOT NULL,
    ID_DIRECCION_FK NUMBER,
    ID_TELEFONO_CONTACTO_FK NUMBER,
    USUARIO_NOMBRE VARCHAR2(100),
    USUARIO_CORREO VARCHAR2(100),
    USUARIO_CONTRASENNA VARCHAR2(100),
    USUARIO_IDENTIFICACION NUMBER,
    USUARIO_FECHA_REGISTRO DATE,
    USUARIO_CUENTA_BANCARIA VARCHAR2(50),
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_USUARIOS_PK PRIMARY KEY (ID_USUARIO_PK),
    CONSTRAINT FIDE_USUARIOS_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK),
    CONSTRAINT FIDE_USUARIOS_ESPECIALIDAD_FK FOREIGN KEY (ID_ESPECIALIDAD_FK) REFERENCES FIDE_ESPECIALIDAD_TB(ID_ESPECIALIDAD_PK),
    CONSTRAINT FIDE_USUARIOS_TIPO_USUARIO_FK FOREIGN KEY (ID_TIPO_USUARIO_FK) REFERENCES FIDE_TIPO_USUARIO_TB(ID_TIPO_USUARIO_PK),
    CONSTRAINT FIDE_USUARIOS_DIRECCION_FK FOREIGN KEY (ID_DIRECCION_FK) REFERENCES FIDE_DIRECCION_TB(ID_DIRECCION_PK),
    CONSTRAINT FIDE_USUARIOS_TELEFONO_CONTACTO_FK FOREIGN KEY (ID_TELEFONO_CONTACTO_FK) REFERENCES FIDE_TELEFONO_CONTACTO_TB(ID_TELEFONO_CONTACTO_PK)
);
/
-- Creacion tabla FIDE_MASCOTA_ESPECIE_TB
CREATE TABLE FIDE_MASCOTA_ESPECIE_TB (
    ID_MASCOTA_ESPECIE_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    NOMBRE_ESPECIE VARCHAR2(100) NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_MASCOTA_ESPECIE_PK PRIMARY KEY (ID_MASCOTA_ESPECIE_PK),
    CONSTRAINT FIDE_MASCOTA_ESPECIE_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_MASCOTA_RAZA_TB
CREATE TABLE FIDE_MASCOTA_RAZA_TB (
    ID_MASCOTA_RAZA_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    NOMBRE_RAZA VARCHAR2(100) NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_MASCOTA_RAZA_PK PRIMARY KEY (ID_MASCOTA_RAZA_PK),
    CONSTRAINT FIDE_MASCOTA_RAZA_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_MASCOTA_TB
CREATE TABLE FIDE_MASCOTA_TB (
    ID_MASCOTA_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    ID_MASCOTA_ESPECIE_FK NUMBER NOT NULL,
    ID_MASCOTA_RAZA_FK NUMBER,
    ID_USUARIO_FK NUMBER,
    NOMBRE_MASCOTA VARCHAR2(100),
    FECHA_NACIMIENTO DATE,
    GENERO VARCHAR2(10) NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_MASCOTA_PK PRIMARY KEY (ID_MASCOTA_PK),
    CONSTRAINT FIDE_MASCOTA_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK),
    CONSTRAINT FIDE_MASCOTA_ESPECIE_FK FOREIGN KEY (ID_MASCOTA_ESPECIE_FK) REFERENCES FIDE_MASCOTA_ESPECIE_TB(ID_MASCOTA_ESPECIE_PK),
    CONSTRAINT FIDE_MASCOTA_RAZA_FK FOREIGN KEY (ID_MASCOTA_RAZA_FK) REFERENCES FIDE_MASCOTA_RAZA_TB(ID_MASCOTA_RAZA_PK),
    CONSTRAINT FIDE_MASCOTA_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK) REFERENCES FIDE_USUARIOS_TB(ID_USUARIO_PK)
);
/
-- Creacion tabla FIDE_TIPO_EXAMEN_TB
CREATE TABLE FIDE_TIPO_EXAMEN_TB (
    ID_TIPO_EXAMEN_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    DESCRIPCION_EXAMEN VARCHAR2(200) NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_TIPO_EXAMEN_PK PRIMARY KEY (ID_TIPO_EXAMEN_PK),
    CONSTRAINT FIDE_TIPO_EXAMEN_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_EXAMENES_TB
CREATE TABLE FIDE_EXAMENES_TB (
    ID_EXAMEN_PK NUMBER NOT NULL,
    ID_MASCOTA_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    ID_TIPO_EXAMEN_FK NUMBER NOT NULL,
    EXAMEN_RESULTADO VARCHAR2(100) NOT NULL,
    EXAMEN_FECHA_SEGUIMIENTO DATE,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_EXAMENES_PK PRIMARY KEY (ID_EXAMEN_PK),
    CONSTRAINT FIDE_EXAMENES_MASCOTA_FK FOREIGN KEY (ID_MASCOTA_FK) REFERENCES FIDE_MASCOTA_TB(ID_MASCOTA_PK),
    CONSTRAINT FIDE_EXAMENES_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK),
    CONSTRAINT FIDE_EXAMENES_TIPO_EXAMEN_FK FOREIGN KEY (ID_TIPO_EXAMEN_FK) REFERENCES FIDE_TIPO_EXAMEN_TB(ID_TIPO_EXAMEN_PK)
);
/
-- Creacion tabla FIDE_CONSULTA_MOTIVO_TB
CREATE TABLE FIDE_CONSULTA_MOTIVO_TB (
    ID_CONSULTA_MOTIVO_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    DESCRIPCION_MOTIVO VARCHAR2(200) NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_CONSULTA_MOTIVO_PK PRIMARY KEY (ID_CONSULTA_MOTIVO_PK),
    CONSTRAINT FIDE_CONSULTA_MOTIVO_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_CONSULTAS_TB
CREATE TABLE FIDE_CONSULTAS_TB (
    ID_CONSULTA_PK NUMBER NOT NULL,
    CONSULTA_FECHA DATE NOT NULL,
    ID_CONSULTA_MOTIVO_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    ID_MASCOTA_FK NUMBER NOT NULL,
    ID_USUARIO_FK NUMBER,
    CONSULTA_OBSERVACIONES VARCHAR2(100),
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_CONSULTAS_PK PRIMARY KEY (ID_CONSULTA_PK),
    CONSTRAINT FIDE_CONSULTAS_MOTIVO_FK FOREIGN KEY (ID_CONSULTA_MOTIVO_FK) REFERENCES FIDE_CONSULTA_MOTIVO_TB(ID_CONSULTA_MOTIVO_PK),
    CONSTRAINT FIDE_CONSULTAS_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK),
    CONSTRAINT FIDE_CONSULTAS_MASCOTA_FK FOREIGN KEY (ID_MASCOTA_FK) REFERENCES FIDE_MASCOTA_TB(ID_MASCOTA_PK),
    CONSTRAINT FIDE_CONSULTAS_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK) REFERENCES FIDE_USUARIOS_TB(ID_USUARIO_PK)
);
/
-- Creacion tabla FIDE_FACTURACIONES_TB
CREATE TABLE FIDE_FACTURACIONES_TB (
    ID_FACTURA_PK varchar2(50),
    ID_CONSULTA_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    FACTURA_FECHA_EMISION DATE NOT NULL,
    FACTURA_MONTO_TOTAL NUMBER NOT NULL,
    FACTURA_DESCUENTO NUMBER,
    FACTURA_IMPUESTOS NUMBER NOT NULL,
    FACTURA_MONTO_FINAL NUMBER NOT NULL,
    FACTURA_SUBTOTAL NUMBER NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_FACTURACIONES_PK PRIMARY KEY (ID_FACTURA_PK),
    CONSTRAINT FIDE_FACTURACIONES_CONSULTA_FK FOREIGN KEY (ID_CONSULTA_FK) REFERENCES FIDE_CONSULTAS_TB(ID_CONSULTA_PK),
    CONSTRAINT FIDE_FACTURACIONES_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_PROVEEDORES_TB
CREATE TABLE FIDE_PROVEEDORES_TB (
    ID_PROVEEDOR_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    ID_DIRECCION_FK NUMBER,
    ID_TELEFONO_CONTACTO_FK NUMBER,
    PROVEEDOR_NOMBRE VARCHAR2(100) NOT NULL,
    PROVEEDOR_CORREO VARCHAR2(100),
    PROVEEDOR_DESCRIPCION_PRODUCTOS VARCHAR2(200),
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_PROVEEDORES_PK PRIMARY KEY (ID_PROVEEDOR_PK),
    CONSTRAINT FIDE_PROVEEDORES_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK),
    CONSTRAINT FIDE_PROVEEDORES_DIRECCION_FK FOREIGN KEY (ID_DIRECCION_FK) REFERENCES FIDE_DIRECCION_TB(ID_DIRECCION_PK),
    CONSTRAINT FIDE_PROVEEDORES_TELEFONO_CONTACTO_FK FOREIGN KEY (ID_TELEFONO_CONTACTO_FK) REFERENCES FIDE_TELEFONO_CONTACTO_TB(ID_TELEFONO_CONTACTO_PK)
);
/
-- Creacion tabla FIDE_PRODUCTOS_TB
CREATE TABLE FIDE_PRODUCTOS_TB (
    ID_PRODUCTO_PK NUMBER NOT NULL,
    ID_PROVEEDOR_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    PRODUCTO_NOMBRE VARCHAR2(100) NOT NULL,
    PRODUCTO_DESCRIPCION VARCHAR2(200) NOT NULL,
    PRODUCTO_PRECIO_UNITARIO NUMBER NOT NULL,
    PRODUCTO_STOCK NUMBER NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_PRODUCTOS_PK PRIMARY KEY (ID_PRODUCTO_PK),
    CONSTRAINT FIDE_PRODUCTOS_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR_FK) REFERENCES FIDE_PROVEEDORES_TB(ID_PROVEEDOR_PK),
    CONSTRAINT FIDE_PRODUCTOS_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_DETALLE_FACTURA_TB
CREATE TABLE FIDE_DETALLE_FACTURA_TB (
    ID_FACTURA_FK varchar2(50),
    LINEA NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    ID_PRODUCTO_FK NUMBER NOT NULL,
    MONTO_UNITARIO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    TOTAL NUMBER NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_DETALLE_FACTURA_PK PRIMARY KEY (ID_FACTURA_FK, LINEA),
    CONSTRAINT FIDE_DETALLE_FACTURA_FACTURA_FK FOREIGN KEY (ID_FACTURA_FK) REFERENCES FIDE_FACTURACIONES_TB(ID_FACTURA_PK),
    CONSTRAINT FIDE_DETALLE_FACTURA_PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES FIDE_PRODUCTOS_TB(ID_PRODUCTO_PK),
    CONSTRAINT FIDE_FACTURA_PRODUCTOS_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_ORDEN_COMPRA_TB
CREATE TABLE FIDE_ORDEN_COMPRA_TB (
    ID_ORDEN_COMPRA_PK NUMBER NOT NULL,
    ID_PROVEEDOR_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    ORDEN_COMPRA_FECHA DATE NOT NULL,
    ORDEN_COMPRA_PRECIO_TOTAL NUMBER NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_ORDEN_COMPRA_PK PRIMARY KEY (ID_ORDEN_COMPRA_PK),
    CONSTRAINT FIDE_ORDEN_COMPRA_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR_FK) REFERENCES FIDE_PROVEEDORES_TB(ID_PROVEEDOR_PK),
    CONSTRAINT FIDE_ORDEN_COMPRA_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_ORDEN_PRODUCTOS_TB
CREATE TABLE FIDE_ORDEN_PRODUCTOS_TB (
    ID_ORDEN_COMPRA_FK NUMBER NOT NULL,
    ID_PRODUCTO_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    ORDEN_PRODUCTO_CANTIDAD NUMBER NOT NULL,
    ORDEN_PRODUCTO_PRECIO_UNITARIO NUMBER NOT NULL,
    ORDEN_PRODUCTO_SUBTOTAL NUMBER NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_ORDEN_PRODUCTOS_PK PRIMARY KEY (ID_ORDEN_COMPRA_FK, ID_PRODUCTO_FK),
    CONSTRAINT FIDE_ORDEN_PRODUCTOS_ORDEN_FK FOREIGN KEY (ID_ORDEN_COMPRA_FK) REFERENCES FIDE_ORDEN_COMPRA_TB(ID_ORDEN_COMPRA_PK),
    CONSTRAINT FIDE_ORDEN_PRODUCTOS_PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES FIDE_PRODUCTOS_TB(ID_PRODUCTO_PK),
    CONSTRAINT FIDE_ORDEN_PRODUCTOS_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_TIPO_VIA_TB
CREATE TABLE FIDE_TIPO_VIA_TB (
    ID_TIPO_VIA_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    TIPO_VIA_DESCRIPCION VARCHAR2(100) NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_TIPO_VIA_PK PRIMARY KEY (ID_TIPO_VIA_PK),
    CONSTRAINT FIDE_TIPO_VIA_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_ROLES_CIRUGIA_TB
CREATE TABLE FIDE_ROLES_CIRUGIA_TB (
    ID_ROL_CIRUGIA_PK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    MEDICO_CIRUJANO VARCHAR2(100) NOT NULL,
    ASISTENTE_ANESTESIOLOGO VARCHAR2(100) NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_ROLES_CIRUGIA_PK PRIMARY KEY (ID_ROL_CIRUGIA_PK),
    CONSTRAINT FIDE_ROLES_CIRUGIA_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_REGISTRO_CIRUGIAS_TB
CREATE TABLE FIDE_REGISTRO_CIRUGIAS_TB (
    ID_CIRUGIA_PK NUMBER NOT NULL,
    CIRUGIA_FECHA_INICIO DATE NOT NULL,
    CIRUGIA_FECHA_FINAL DATE NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    ID_MASCOTA_FK NUMBER NOT NULL,
    CIRUGIA_ANOTACIONES VARCHAR2(100),
    CIRUGIA_DIAG_PREVIO VARCHAR2(100),
    CIRUGIA_DIAG_POST VARCHAR2(100),
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_REGISTRO_CIRUGIAS_PK PRIMARY KEY (ID_CIRUGIA_PK),
    CONSTRAINT FIDE_REGISTRO_CIRUGIAS_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK),
    CONSTRAINT FIDE_REGISTRO_CIRUGIAS_MASCOTA_FK FOREIGN KEY (ID_MASCOTA_FK) REFERENCES FIDE_MASCOTA_TB(ID_MASCOTA_PK)
);
/
-- Creacion tabla FIDE_CIRUGIAS_MEDICAMENTOS_TB
CREATE TABLE FIDE_CIRUGIAS_MEDICAMENTOS_TB (
    ID_CIRUGIA_FK NUMBER NOT NULL,
    ID_PRODUCTO_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    ID_TIPO_VIA_FK NUMBER NOT NULL,
    CIRUGIA_MEDICAMENTO_DOSIS VARCHAR2(100) NOT NULL,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_CIRUGIAS_MEDICAMENTOS_PK PRIMARY KEY (ID_CIRUGIA_FK, ID_PRODUCTO_FK),
    CONSTRAINT FIDE_CIRUGIAS_MEDICAMENTOS_CIRUGIA_FK FOREIGN KEY (ID_CIRUGIA_FK) REFERENCES FIDE_REGISTRO_CIRUGIAS_TB(ID_CIRUGIA_PK),
    CONSTRAINT FIDE_CIRUGIAS_MEDICAMENTOS_PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES FIDE_PRODUCTOS_TB(ID_PRODUCTO_PK),
    CONSTRAINT FIDE_CIRUGIAS_MEDICAMENTOS_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK),
    CONSTRAINT FIDE_CIRUGIAS_MEDICAMENTOS_TIPO_VIA_FK FOREIGN KEY (ID_TIPO_VIA_FK) REFERENCES FIDE_TIPO_VIA_TB(ID_TIPO_VIA_PK)
);
/
-- Creacion tabla FIDE_CIRUGIAS_PERSONAL_TB
CREATE TABLE FIDE_CIRUGIAS_PERSONAL_TB (
    ID_CIRUGIA_FK NUMBER NOT NULL,
    ID_USUARIO_FK NUMBER NOT NULL,
    ID_ROL_CIRUGIA_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    ID_TIPO_USUARIO_FK NUMBER NOT NULL,
    ANOTACIONES_ADICIONALES VARCHAR2(50),
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_CIRUGIAS_PERSONAL_PK PRIMARY KEY (ID_CIRUGIA_FK, ID_USUARIO_FK, ID_ROL_CIRUGIA_FK),
    CONSTRAINT FIDE_CIRUGIAS_PERSONAL_CIRUGIA_FK FOREIGN KEY (ID_CIRUGIA_FK) REFERENCES FIDE_REGISTRO_CIRUGIAS_TB(ID_CIRUGIA_PK),
    CONSTRAINT FIDE_CIRUGIAS_PERSONAL_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK) REFERENCES FIDE_USUARIOS_TB(ID_USUARIO_PK),
    CONSTRAINT FIDE_CIRUGIAS_PERSONAL_ROL_FK FOREIGN KEY (ID_ROL_CIRUGIA_FK) REFERENCES FIDE_ROLES_CIRUGIA_TB(ID_ROL_CIRUGIA_PK),
    CONSTRAINT FIDE_CIRUGIAS_PERSONAL_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK),
    CONSTRAINT FIDE_CIRUGIAS_PERSONAL_TIPO_USUARIO_FK FOREIGN KEY (ID_TIPO_USUARIO_FK) REFERENCES FIDE_TIPO_USUARIO_TB(ID_TIPO_USUARIO_PK)
);
/
-- Creacion tabla FIDE_HISTORIALES_MEDICOS_TB
CREATE TABLE FIDE_HISTORIALES_MEDICOS_TB (
    ID_MASCOTA_FK NUMBER NOT NULL,
    ID_CONSULTA_FK NUMBER NOT NULL,
    ID_USUARIO_FK NUMBER,
    ID_TIPO_USUARIO_FK NUMBER,
    ID_ESTADO_FK NUMBER NOT NULL,
    HISTORIAL_FECHA_REGISTRO DATE NOT NULL,
    HISTORIAL_DIAGNOSTICO VARCHAR2(100),
    HISTORIAL_TRATAMIENTO VARCHAR2(100),
    HISTORIAL_NOTAS VARCHAR2(100),
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_HISTORIALES_MEDICOS_PK PRIMARY KEY (ID_MASCOTA_FK, ID_CONSULTA_FK),
    CONSTRAINT FIDE_HISTORIALES_MEDICOS_MASCOTA_FK FOREIGN KEY (ID_MASCOTA_FK) REFERENCES FIDE_MASCOTA_TB(ID_MASCOTA_PK),
    CONSTRAINT FIDE_HISTORIALES_MEDICOS_CONSULTA_FK FOREIGN KEY (ID_CONSULTA_FK) REFERENCES FIDE_CONSULTAS_TB(ID_CONSULTA_PK),
    CONSTRAINT FIDE_HISTORIALES_MEDICOS_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK) REFERENCES FIDE_USUARIOS_TB(ID_USUARIO_PK),
    CONSTRAINT FIDE_HISTORIALES_MEDICOS_TIPO_USUARIO_FK FOREIGN KEY (ID_TIPO_USUARIO_FK) REFERENCES FIDE_TIPO_USUARIO_TB(ID_TIPO_USUARIO_PK),
    CONSTRAINT FIDE_HISTORIALES_MEDICOS_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
-- Creacion tabla FIDE_PAGOS_PLANILLAS_TB
CREATE TABLE FIDE_PAGOS_PLANILLAS_TB (
    ID_PAGO_PLANILLA_PK NUMBER NOT NULL,
    ID_USUARIO_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,
    PAGO_FECHA DATE NOT NULL,
    PAGO_SALARIO_BRUTO NUMBER NOT NULL,
    PAGO_SALARIO_NETO NUMBER NOT NULL,
    PAGO_HORAS_EXTRA NUMBER,
    PAGO_VACACIONES NUMBER,
    CREATED_BY VARCHAR2(50),
    CREATION_DATE DATE,
    MODIFIED_BY VARCHAR2(50),
    MODIFICATION_DATE DATE,
    CONSTRAINT FIDE_PAGOS_PLANILLAS_PK PRIMARY KEY (ID_PAGO_PLANILLA_PK),
    CONSTRAINT FIDE_PAGOS_PLANILLAS_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK) REFERENCES FIDE_USUARIOS_TB(ID_USUARIO_PK),
    CONSTRAINT FIDE_PAGOS_PLANILLAS_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK) REFERENCES FIDE_ESTADO_TB(ID_ESTADO_PK)
);
/
/*------------------------------------------------------------------------------
---------------------------------ALTER DE TABLAS--------------------------------
------------------------------------------------------------------------------*/
ALTER TABLE FIDE_ESTADO_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_DIRECCION_PROVINCIA_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_DIRECCION_CANTON_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_DIRECCION_DISTRITO_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_DIRECCION_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_TELEFONO_CONTACTO_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_TIPO_USUARIO_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_ESPECIALIDAD_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_USUARIOS_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_MASCOTA_ESPECIE_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_MASCOTA_RAZA_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_MASCOTA_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_TIPO_EXAMEN_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_EXAMENES_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_CONSULTA_MOTIVO_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_CONSULTAS_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_FACTURACIONES_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_PROVEEDORES_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_PRODUCTOS_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_DETALLE_FACTURA_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_ORDEN_PRODUCTOS_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_ORDEN_COMPRA_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_TIPO_VIA_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_ROLES_CIRUGIA_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_REGISTRO_CIRUGIAS_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_CIRUGIAS_MEDICAMENTOS_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_CIRUGIAS_PERSONAL_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_HISTORIALES_MEDICOS_TB ADD ACCION VARCHAR2(15);
ALTER TABLE FIDE_PAGOS_PLANILLAS_TB ADD ACCION VARCHAR2(15);
/
/*------------------------------------------------------------------------------
-----------------------------CREACION PACKAGE-----------------------------------
------------------------------------------------------------------------------*/



/*------------------------------------------------------------------------------
-----------------------------CREACION SECUENCIAS--------------------------------
------------------------------------------------------------------------------*/
-- Secuencia ID_DIRECCION_PROVINCIA_PK_SEQ
CREATE SEQUENCE ID_DIRECCION_PROVINCIA_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_DIRECCION_CANTON_PK_SEQ
CREATE SEQUENCE ID_DIRECCION_CANTON_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_DIRECCION_DISTRITO_PK_SEQ
CREATE SEQUENCE ID_DIRECCION_DISTRITO_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_DIRECCION_PK_SEQ
CREATE SEQUENCE ID_DIRECCION_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_TELEFONO_CONTACTO_PK_SEQ
CREATE SEQUENCE ID_TELEFONO_CONTACTO_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_TIPO_USUARIO_PK_SEQ
CREATE SEQUENCE ID_TIPO_USUARIO_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_ESPECIALIDAD_PK_SEQ
CREATE SEQUENCE ID_ESPECIALIDAD_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_USUARIO_PK_SEQ
CREATE SEQUENCE ID_USUARIO_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_MASCOTA_ESPECIE_PK_SEQ
CREATE SEQUENCE ID_MASCOTA_ESPECIE_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_MASCOTA_RAZA_PK_SEQ
CREATE SEQUENCE ID_MASCOTA_RAZA_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_MASCOTA_PK_SEQ
CREATE SEQUENCE ID_MASCOTA_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_TIPO_EXAMEN_PK_SEQ
CREATE SEQUENCE ID_TIPO_EXAMEN_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_EXAMEN_PK_SEQ
CREATE SEQUENCE ID_EXAMEN_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_CONSULTA_MOTIVO_PK_SEQ
CREATE SEQUENCE ID_CONSULTA_MOTIVO_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_CONSULTA_PK_SEQ
CREATE SEQUENCE ID_CONSULTA_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_FACTURA_PK_SEQ
CREATE SEQUENCE ID_FACTURA_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_PROVEEDOR_PK_SEQ
CREATE SEQUENCE ID_PROVEEDOR_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_PRODUCTO_PK_SEQ
CREATE SEQUENCE ID_PRODUCTO_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_ORDEN_COMPRA_PK_SEQ
CREATE SEQUENCE ID_ORDEN_COMPRA_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_TIPO_VIA_PK_SEQ
CREATE SEQUENCE ID_TIPO_VIA_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_ROL_CIRUGIA_PK_SEQ
CREATE SEQUENCE ID_ROL_CIRUGIA_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_CIRUGIA_PK_SEQ
CREATE SEQUENCE ID_CIRUGIA_PK_SEQ START WITH 1 INCREMENT BY 1;
/
-- Secuencia ID_PAGO_PLANILLA_PK_SEQ
CREATE SEQUENCE ID_PAGO_PLANILLA_PK_SEQ START WITH 1 INCREMENT BY 1;
/
/*------------------------------------------------------------------------------
------------------------------CREACION TRIGGERS---------------------------------
------------------------------------------------------------------------------*/
-- Trigger FIDE_DIRECCION_PROVINCIA_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_PROVINCIA_TB_TRG
BEFORE INSERT ON FIDE_DIRECCION_PROVINCIA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_DIRECCION_PROVINCIA_PK := ID_DIRECCION_PROVINCIA_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_DIRECCION_CANTON_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_CANTON_TB_TRG
BEFORE INSERT ON FIDE_DIRECCION_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.ID_DIRECCION_CANTON_PK := ID_DIRECCION_CANTON_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_DIRECCION_DISTRITO_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_DISTRITO_TB_TRG
BEFORE INSERT ON FIDE_DIRECCION_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_DIRECCION_DISTRITO_PK := ID_DIRECCION_DISTRITO_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_DIRECCION_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.ID_DIRECCION_PK := ID_DIRECCION_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_TELEFONO_CONTACTO_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_TELEFONO_CONTACTO_TB_TRG
BEFORE INSERT ON FIDE_TELEFONO_CONTACTO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_TELEFONO_CONTACTO_PK := ID_TELEFONO_CONTACTO_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_TIPO_USUARIO_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_TIPO_USUARIO_TB_TRG
BEFORE INSERT ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_TIPO_USUARIO_PK := ID_TIPO_USUARIO_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_ESPECIALIDAD_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_ESPECIALIDAD_TB_TRG
BEFORE INSERT ON FIDE_ESPECIALIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESPECIALIDAD_PK := ID_ESPECIALIDAD_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_USUARIOS_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_USUARIOS_TB_TRG
BEFORE INSERT ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_USUARIO_PK := ID_USUARIO_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_MASCOTA_ESPECIE_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_MASCOTA_ESPECIE_TB_TRG
BEFORE INSERT ON FIDE_MASCOTA_ESPECIE_TB
FOR EACH ROW
BEGIN
    :NEW.ID_MASCOTA_ESPECIE_PK := ID_MASCOTA_ESPECIE_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_MASCOTA_RAZA_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_MASCOTA_RAZA_TB_TRG
BEFORE INSERT ON FIDE_MASCOTA_RAZA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_MASCOTA_RAZA_PK := ID_MASCOTA_RAZA_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_MASCOTA_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_MASCOTA_TB_TRG
BEFORE INSERT ON FIDE_MASCOTA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_MASCOTA_PK := ID_MASCOTA_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_TIPO_EXAMEN_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_TIPO_EXAMEN_TB_TRG
BEFORE INSERT ON FIDE_TIPO_EXAMEN_TB
FOR EACH ROW
BEGIN
    :NEW.ID_TIPO_EXAMEN_PK := ID_TIPO_EXAMEN_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_EXAMENES_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_EXAMENES_TB_TRG
BEFORE INSERT ON FIDE_EXAMENES_TB
FOR EACH ROW
BEGIN
    :NEW.ID_EXAMEN_PK := ID_EXAMEN_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_CONSULTA_MOTIVO_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_CONSULTA_MOTIVO_TB_TRG
BEFORE INSERT ON FIDE_CONSULTA_MOTIVO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_CONSULTA_MOTIVO_PK := ID_CONSULTA_MOTIVO_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_CONSULTAS_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_CONSULTAS_TB_TRG
BEFORE INSERT ON FIDE_CONSULTAS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_CONSULTA_PK := ID_CONSULTA_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_FACTURACIONES_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_FACTURACIONES_TB_TRG
BEFORE INSERT ON FIDE_FACTURACIONES_TB
FOR EACH ROW
BEGIN
    :NEW.ID_FACTURA_PK := ID_FACTURA_PK_FN();
END;
/
-- Trigger FIDE_PROVEEDORES_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_PROVEEDORES_TB_TRG
BEFORE INSERT ON FIDE_PROVEEDORES_TB
FOR EACH ROW
BEGIN
    :NEW.ID_PROVEEDOR_PK := ID_PROVEEDOR_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_PRODUCTOS_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_PRODUCTOS_TB_TRG
BEFORE INSERT ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_PRODUCTO_PK := ID_PRODUCTO_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_ORDEN_COMPRA_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_ORDEN_COMPRA_TB_TRG
BEFORE INSERT ON FIDE_ORDEN_COMPRA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ORDEN_COMPRA_PK := ID_ORDEN_COMPRA_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_TIPO_VIA_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_TIPO_VIA_TB_TRG
BEFORE INSERT ON FIDE_TIPO_VIA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_TIPO_VIA_PK := ID_TIPO_VIA_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_ROLES_CIRUGIA_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_ROLES_CIRUGIA_TB_TRG
BEFORE INSERT ON FIDE_ROLES_CIRUGIA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ROL_CIRUGIA_PK := ID_ROL_CIRUGIA_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_REGISTRO_CIRUGIAS_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_REGISTRO_CIRUGIAS_TB_TRG
BEFORE INSERT ON FIDE_REGISTRO_CIRUGIAS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_CIRUGIA_PK := ID_CIRUGIA_PK_SEQ.NEXTVAL;
END;
/
-- Trigger FIDE_PAGOS_PLANILLAS_TB_TRG
CREATE OR REPLACE TRIGGER FIDE_PAGOS_PLANILLAS_TB_TRG
BEFORE INSERT ON FIDE_PAGOS_PLANILLAS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_PAGO_PLANILLA_PK := ID_PAGO_PLANILLA_PK_SEQ.NEXTVAL;
END;
/
-- Accion FIDE_ESTADO_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_ESTADO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
    :NEW.ACCION:='INSERT';
    ELSIF UPDATING THEN
    :NEW.ACCION:='UPDATE';
    END IF;
END;
/
-- Accion FIDE_DIRECCION_PROVINCIA_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_DIRECCION_PROVINCIA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
    :NEW.ACCION:='INSERT';
    ELSIF UPDATING THEN
    :NEW.ACCION:='UPDATE';
    END IF;
END;
/
-- Accion FIDE_DIRECCION_CANTON_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_DIRECCION_CANTON_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_CANTON_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_DIRECCION_DISTRITO_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_DIRECCION_DISTRITO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_DIRECCION_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_DIRECCION_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_TELEFONO_CONTACTO_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_TELEFONO_CONTACTO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_TELEFONO_CONTACTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_TIPO_USUARIO_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_TIPO_USUARIO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_ESPECIALIDAD_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_ESPECIALIDAD_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESPECIALIDAD_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_USUARIOS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_USUARIOS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_MASCOTA_ESPECIE_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_MASCOTA_ESPECIE_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_MASCOTA_ESPECIE_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_MASCOTA_RAZA_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_MASCOTA_RAZA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_MASCOTA_RAZA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_MASCOTA_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_MASCOTA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_MASCOTA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_TIPO_EXAMEN_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_TIPO_EXAMEN_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_EXAMEN_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_EXAMENES_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_EXAMENES_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_EXAMENES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_CONSULTA_MOTIVO_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_CONSULTA_MOTIVO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_CONSULTA_MOTIVO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_CONSULTAS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_CONSULTAS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_CONSULTAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_FACTURACIONES_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_FACTURACIONES_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURACIONES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_PROVEEDORES_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_PROVEEDORES_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVEEDORES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_PRODUCTOS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_PRODUCTOS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_DETALLE_FACTURA_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_DETALLE_FACTURA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_ORDEN_PRODUCTOS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_ORDEN_PRODUCTOS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_ORDEN_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_ORDEN_COMPRA_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_ORDEN_COMPRA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_ORDEN_COMPRA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_TIPO_VIA_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_TIPO_VIA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_VIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_ROLES_CIRUGIA_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_ROLES_CIRUGIA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROLES_CIRUGIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_REGISTRO_CIRUGIAS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_REGISTRO_CIRUGIAS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_REGISTRO_CIRUGIAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_CIRUGIAS_MEDICAMENTOS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_CIRUGIAS_MEDICAMENTOS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_CIRUGIAS_MEDICAMENTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_CIRUGIAS_PERSONAL_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_CIRUGIAS_PERSONAL_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_CIRUGIAS_PERSONAL_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_HISTORIALES_MEDICOS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_HISTORIALES_MEDICOS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_HISTORIALES_MEDICOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_PAGOS_PLANILLAS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_PAGOS_PLANILLAS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_PAGOS_PLANILLAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Modification Date FIDE_ESTADO_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_ESTADO_TB_TRG
BEFORE UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE:=SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/
-- Modification Date FIDE_DIRECCION_PROVINCIA_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_DIRECCION_PROVINCIA_TB_TRG
BEFORE UPDATE ON FIDE_DIRECCION_PROVINCIA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_DIRECCION_CANTON_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_DIRECCION_CANTON_TB_TRG
BEFORE UPDATE ON FIDE_DIRECCION_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_DIRECCION_DISTRITO_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_DIRECCION_DISTRITO_TB_TRG
BEFORE UPDATE ON FIDE_DIRECCION_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_DIRECCION_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_DIRECCION_TB_TRG
BEFORE UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_TELEFONO_CONTACTO_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_TELEFONO_CONTACTO_TB_TRG
BEFORE UPDATE ON FIDE_TELEFONO_CONTACTO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_TIPO_USUARIO_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_TIPO_USUARIO_TB_TRG
BEFORE UPDATE ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_ESPECIALIDAD_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_ESPECIALIDAD_TB_TRG
BEFORE UPDATE ON FIDE_ESPECIALIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_USUARIOS_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_USUARIOS_TB_TRG
BEFORE UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_MASCOTA_ESPECIE_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_MASCOTA_ESPECIE_TB_TRG
BEFORE UPDATE ON FIDE_MASCOTA_ESPECIE_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_MASCOTA_RAZA_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_MASCOTA_RAZA_TB_TRG
BEFORE UPDATE ON FIDE_MASCOTA_RAZA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_MASCOTA_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_MASCOTA_TB_TRG
BEFORE UPDATE ON FIDE_MASCOTA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_TIPO_EXAMEN_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_TIPO_EXAMEN_TB_TRG
BEFORE UPDATE ON FIDE_TIPO_EXAMEN_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_EXAMENES_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_EXAMENES_TB_TRG
BEFORE UPDATE ON FIDE_EXAMENES_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_CONSULTA_MOTIVO_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_CONSULTA_MOTIVO_TB_TRG
BEFORE UPDATE ON FIDE_CONSULTA_MOTIVO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_CONSULTAS_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_CONSULTAS_TB_TRG
BEFORE UPDATE ON FIDE_CONSULTAS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_FACTURACIONES_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_FACTURACIONES_TB_TRG
BEFORE UPDATE ON FIDE_FACTURACIONES_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_PROVEEDORES_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_PROVEEDORES_TB_TRG
BEFORE UPDATE ON FIDE_PROVEEDORES_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_PRODUCTOS_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_PRODUCTOS_TB_TRG
BEFORE UPDATE ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_DETALLE_FACTURA_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_DETALLE_FACTURA_TB_TRG
BEFORE UPDATE ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_ORDEN_PRODUCTOS_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_ORDEN_PRODUCTOS_TB_TRG
BEFORE UPDATE ON FIDE_ORDEN_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_ORDEN_COMPRA_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_ORDEN_COMPRA_TB_TRG
BEFORE UPDATE ON FIDE_ORDEN_COMPRA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_TIPO_VIA_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_TIPO_VIA_TB_TRG
BEFORE UPDATE ON FIDE_TIPO_VIA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_ROLES_CIRUGIA_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_ROLES_CIRUGIA_TB_TRG
BEFORE UPDATE ON FIDE_ROLES_CIRUGIA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_REGISTRO_CIRUGIAS_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_REGISTRO_CIRUGIAS_TB_TRG
BEFORE UPDATE ON FIDE_REGISTRO_CIRUGIAS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_CIRUGIAS_MEDICAMENTOS_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_CIRUGIAS_MEDICAMENTOS_TB_TRG
BEFORE UPDATE ON FIDE_CIRUGIAS_MEDICAMENTOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_CIRUGIAS_PERSONAL_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_CIRUGIAS_PERSONAL_TB_TRG
BEFORE UPDATE ON FIDE_CIRUGIAS_PERSONAL_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_HISTORIALES_MEDICOS_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_HISTORIALES_MEDICOS_TB_TRG
BEFORE UPDATE ON FIDE_HISTORIALES_MEDICOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/

-- Modification Date FIDE_PAGOS_PLANILLAS_TB
CREATE OR REPLACE TRIGGER FECHA_MODIFICACION_FIDE_PAGOS_PLANILLAS_TB_TRG
BEFORE UPDATE ON FIDE_PAGOS_PLANILLAS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICATION_DATE := SYSTIMESTAMP;
    :NEW.MODIFIED_BY:=USER;
END;
/
-- Modification Date FIDE_ESTADO_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_ESTADO_TB_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE:=SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_DIRECCION_PROVINCIA_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_DIRECCION_PROVINCIA_TB_TRG
BEFORE INSERT ON FIDE_DIRECCION_PROVINCIA_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_DIRECCION_CANTON_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_DIRECCION_CANTON_TB_TRG
BEFORE INSERT ON FIDE_DIRECCION_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_DIRECCION_DISTRITO_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_DIRECCION_DISTRITO_TB_TRG
BEFORE INSERT ON FIDE_DIRECCION_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_DIRECCION_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_DIRECCION_TB_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_TELEFONO_CONTACTO_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_TELEFONO_CONTACTO_TB_TRG
BEFORE INSERT ON FIDE_TELEFONO_CONTACTO_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_TIPO_USUARIO_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_TIPO_USUARIO_TB_TRG
BEFORE INSERT ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_ESPECIALIDAD_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_ESPECIALIDAD_TB_TRG
BEFORE INSERT ON FIDE_ESPECIALIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_USUARIOS_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_USUARIOS_TB_TRG
BEFORE INSERT ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_MASCOTA_ESPECIE_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_MASCOTA_ESPECIE_TB_TRG
BEFORE INSERT ON FIDE_MASCOTA_ESPECIE_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_MASCOTA_RAZA_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_MASCOTA_RAZA_TB_TRG
BEFORE INSERT ON FIDE_MASCOTA_RAZA_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_MASCOTA_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_MASCOTA_TB_TRG
BEFORE INSERT ON FIDE_MASCOTA_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_TIPO_EXAMEN_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_TIPO_EXAMEN_TB_TRG
BEFORE INSERT ON FIDE_TIPO_EXAMEN_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_EXAMENES_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_EXAMENES_TB_TRG
BEFORE INSERT ON FIDE_EXAMENES_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_CONSULTA_MOTIVO_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_CONSULTA_MOTIVO_TB_TRG
BEFORE INSERT ON FIDE_CONSULTA_MOTIVO_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_CONSULTAS_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_CONSULTAS_TB_TRG
BEFORE INSERT ON FIDE_CONSULTAS_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_FACTURACIONES_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_FACTURACIONES_TB_TRG
BEFORE INSERT ON FIDE_FACTURACIONES_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/

-- Creation Date FIDE_PROVEEDORES_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_PROVEEDORES_TB_TRG
BEFORE INSERT ON FIDE_PROVEEDORES_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_PRODUCTOS_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_PRODUCTOS_TB_TRG
BEFORE INSERT ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_DETALLE_FACTURA_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_DETALLE_FACTURA_TB_TRG
BEFORE INSERT ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_ORDEN_PRODUCTOS_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_ORDEN_PRODUCTOS_TB_TRG
BEFORE INSERT ON FIDE_ORDEN_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_ORDEN_COMPRA_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_ORDEN_COMPRA_TB_TRG
BEFORE INSERT ON FIDE_ORDEN_COMPRA_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_TIPO_VIA_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_TIPO_VIA_TB_TRG
BEFORE INSERT ON FIDE_TIPO_VIA_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_ROLES_CIRUGIA_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_ROLES_CIRUGIA_TB_TRG
BEFORE INSERT ON FIDE_ROLES_CIRUGIA_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_REGISTRO_CIRUGIAS_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_REGISTRO_CIRUGIAS_TB_TRG
BEFORE INSERT ON FIDE_REGISTRO_CIRUGIAS_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_CIRUGIAS_MEDICAMENTOS_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_CIRUGIAS_MEDICAMENTOS_TB_TRG
BEFORE INSERT ON FIDE_CIRUGIAS_MEDICAMENTOS_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_CIRUGIAS_PERSONAL_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_CIRUGIAS_PERSONAL_TB_TRG
BEFORE INSERT ON FIDE_CIRUGIAS_PERSONAL_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_HISTORIALES_MEDICOS_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_HISTORIALES_MEDICOS_TB_TRG
BEFORE INSERT ON FIDE_HISTORIALES_MEDICOS_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
-- Creation Date FIDE_PAGOS_PLANILLAS_TB
CREATE OR REPLACE TRIGGER FECHA_CREACION_FIDE_PAGOS_PLANILLAS_TB_TRG
BEFORE INSERT ON FIDE_PAGOS_PLANILLAS_TB
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := SYSTIMESTAMP;
    :NEW.CREATED_BY:=USER;
END;
/
/*------------------------------------------------------------------------------
---------------------------------CREACION DE VISTAS-----------------------------
------------------------------------------------------------------------------*/
-- CREACION VISTA DE FACTURA
CREATE OR REPLACE VIEW FACTURA_DETALLES_V AS
SELECT
    F.ID_FACTURA_PK AS FACTURA_ID,
    F.FACTURA_FECHA_EMISION AS FECHA_EMISION,
    F.FACTURA_MONTO_TOTAL AS MONTO_TOTAL,
    F.FACTURA_DESCUENTO AS DESCUENTO,
    F.FACTURA_IMPUESTOS AS IMPUESTOS,
    F.FACTURA_MONTO_FINAL AS MONTO_FINAL,
    DF.LINEA AS LINEA_DETALLE,
    P.PRODUCTO_NOMBRE AS PRODUCTO,
    DF.CANTIDAD AS CANTIDAD,
    DF.MONTO_UNITARIO AS PRECIO_UNITARIO,
    DF.TOTAL AS SUBTOTAL
FROM
    FIDE_FACTURACIONES_TB F
    JOIN FIDE_DETALLE_FACTURA_TB DF ON F.ID_FACTURA_PK = DF.ID_FACTURA_FK
    JOIN FIDE_PRODUCTOS_TB P ON DF.ID_PRODUCTO_FK = P.ID_PRODUCTO_PK
WHERE
    F.ID_ESTADO_FK = 1;
/
-- CREACION VISTA DE INFORMACION DE MASCOTAS
CREATE OR REPLACE VIEW MASCOTA_DETALLES_V AS
SELECT
    M.ID_MASCOTA_PK AS MASCOTA_ID,
    M.NOMBRE_MASCOTA AS NOMBRE,
    M.FECHA_NACIMIENTO AS FECHA_NACIMIENTO,
    M.GENERO AS GENERO,
    ME.NOMBRE_ESPECIE AS ESPECIE,
    MR.NOMBRE_RAZA AS RAZA,
    U.USUARIO_NOMBRE AS DUENNO,
    U.USUARIO_CORREO AS CORREO_DUENNO
FROM
    FIDE_MASCOTA_TB M
    JOIN FIDE_MASCOTA_ESPECIE_TB ME ON M.ID_MASCOTA_ESPECIE_FK = ME.ID_MASCOTA_ESPECIE_PK
    JOIN FIDE_MASCOTA_RAZA_TB MR ON M.ID_MASCOTA_RAZA_FK = MR.ID_MASCOTA_RAZA_PK
    JOIN FIDE_USUARIOS_TB U ON M.ID_USUARIO_FK = U.ID_USUARIO_PK
WHERE
    M.ID_ESTADO_FK = 1;
/
-- CREACION VISTA DE INFORMACION DE CLIENTES
CREATE OR REPLACE VIEW INFO_CLIENTE_V AS
SELECT
    U.ID_USUARIO_PK AS USUARIO_ID,
    U.USUARIO_NOMBRE AS NOMBRE,
    U.USUARIO_CORREO AS CORREO,
    U.USUARIO_IDENTIFICACION AS IDENTIFICACION,
    U.USUARIO_FECHA_REGISTRO AS FECHA_REGISTRO,
    D.DIRECCION_SENNAS AS DIRECCION,
    DP.NOMBRE_PROVINCIA AS PROVINCIA,
    DC.NOMBRE_CANTON AS CANTON,
    DD.NOMBRE_DISTRITO AS DISTRITO,
    TC.TELEFONO_CONTACTO AS TELEFONO
FROM
    FIDE_USUARIOS_TB U
    JOIN FIDE_DIRECCION_TB D ON U.ID_DIRECCION_FK = D.ID_DIRECCION_PK
    JOIN FIDE_DIRECCION_PROVINCIA_TB DP ON D.ID_DIRECCION_PROVINCIA_FK = DP.ID_DIRECCION_PROVINCIA_PK
    JOIN FIDE_DIRECCION_CANTON_TB DC ON D.ID_DIRECCION_CANTON_FK = DC.ID_DIRECCION_CANTON_PK
    JOIN FIDE_DIRECCION_DISTRITO_TB DD ON D.ID_DIRECCION_DISTRITO_FK = DD.ID_DIRECCION_DISTRITO_PK
    JOIN FIDE_TELEFONO_CONTACTO_TB TC ON U.ID_TELEFONO_CONTACTO_FK = TC.ID_TELEFONO_CONTACTO_PK
WHERE
    U.ID_ESTADO_FK = 1
    and 
    U.ID_TIPO_USUARIO_FK = 8;
    
/
-- CREACION VISTA DE HISTORIAL MEDICO DE MASCOTA
CREATE OR REPLACE VIEW HISTORIAL_MEDICO_V AS
SELECT
    HM.ID_HISTORIAL_MEDICO_PK AS HISTORIAL_ID,
    M.NOMBRE_MASCOTA AS MASCOTA,
    HM.HISTORIAL_FECHA_REGISTRO AS FECHA_REGISTRO,
    HM.HISTORIAL_DIAGNOSTICO AS DIAGNOSTICO,
    HM.HISTORIAL_TRATAMIENTO AS TRATAMIENTO,
    HM.HISTORIAL_NOTAS AS NOTAS,
    C.CONSULTA_FECHA AS FECHA_CONSULTA,
    CM.DESCRIPCION_MOTIVO AS MOTIVO_CONSULTA
FROM
    FIDE_HISTORIALES_MEDICOS_TB HM
    JOIN FIDE_MASCOTA_TB M ON HM.ID_MASCOTA_FK = M.ID_MASCOTA_PK
    JOIN FIDE_CONSULTAS_TB C ON HM.ID_CONSULTA_FK = C.ID_CONSULTA_PK
    JOIN FIDE_CONSULTA_MOTIVO_TB CM ON C.ID_CONSULTA_MOTIVO_FK = CM.ID_CONSULTA_MOTIVO_PK
WHERE
    HM.ID_ESTADO_FK = 1;
/
-- CREACION VISTA DE PRODUCTOS
CREATE OR REPLACE VIEW PRODUCTOS_DETALLES_V AS
SELECT
    P.ID_PRODUCTO_PK AS PRODUCTO_ID,
    P.PRODUCTO_NOMBRE AS NOMBRE,
    P.PRODUCTO_DESCRIPCION AS DESCRIPCION,
    P.PRODUCTO_PRECIO_UNITARIO AS PRECIO_UNITARIO,
    P.PRODUCTO_STOCK AS STOCK,
    PR.PROVEEDOR_NOMBRE AS PROVEEDOR,
    PR.PROVEEDOR_CORREO AS CORREO_PROVEEDOR,
    E.ESTADO_DESCRIPCION AS ESTADO
FROM
    FIDE_PRODUCTOS_TB P
    JOIN FIDE_PROVEEDORES_TB PR ON P.ID_PROVEEDOR_FK = PR.ID_PROVEEDOR_PK
    JOIN FIDE_ESTADO_TB E ON P.ID_ESTADO_FK = E.ID_ESTADO_PK
WHERE
    P.ID_ESTADO_FK = 1;

-- Vista para FIDE_ESTADO_TB
CREATE OR REPLACE VIEW FIDE_ESTADO_V AS
SELECT ID_ESTADO_PK, ESTADO_DESCRIPCION, CREATED_BY, CREATION_DATE, MODIFIED_BY, MODIFICATION_DATE, ACCION
FROM FIDE_ESTADO_TB;

-- Vista para FIDE_DIRECCION_PROVINCIA_TB
CREATE OR REPLACE VIEW FIDE_DIRECCION_PROVINCIA_V AS
SELECT ID_DIRECCION_PROVINCIA_PK, ID_ESTADO_FK, NOMBRE_PROVINCIA,
       CREATED_BY, CREATION_DATE, MODIFIED_BY, MODIFICATION_DATE, ACCION
FROM FIDE_DIRECCION_PROVINCIA_TB;

-- Vista para FIDE_DIRECCION_CANTON_TB
CREATE OR REPLACE VIEW FIDE_DIRECCION_CANTON_V AS
SELECT ID_DIRECCION_CANTON_PK, ID_ESTADO_FK, NOMBRE_CANTON,
       CREATED_BY, CREATION_DATE, MODIFIED_BY, MODIFICATION_DATE, ACCION
FROM FIDE_DIRECCION_CANTON_TB;

-- Vista para FIDE_DIRECCION_DISTRITO_TB
CREATE OR REPLACE VIEW FIDE_DIRECCION_DISTRITO_V AS
SELECT ID_DIRECCION_DISTRITO_PK, ID_ESTADO_FK, NOMBRE_DISTRITO,
       CREATED_BY, CREATION_DATE, MODIFIED_BY, MODIFICATION_DATE, ACCION
FROM FIDE_DIRECCION_DISTRITO_TB;

-- Vista para FIDE_DIRECCION_TB
CREATE OR REPLACE VIEW FIDE_DIRECCION_V AS
SELECT ID_DIRECCION_PK, ID_ESTADO_FK, ID_DIRECCION_PROVINCIA_FK,
       ID_DIRECCION_CANTON_FK, ID_DIRECCION_DISTRITO_FK,
       DIRECCION_SENNAS, CREATED_BY, CREATION_DATE,
       MODIFIED_BY, MODIFICATION_DATE, ACCION
FROM FIDE_DIRECCION_TB;