-- Accion FIDE_ESTADO_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_ESTADO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
    :NEW.ACCION:='INSERT';
    ELSIF UPDATING THEN
    :NEW.ACCION:='UPDATE';
    END IF;
END;
/
-- Accion FIDE_DIRECCION_PROVINCIA_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_DIRECCION_PROVINCIA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
    :NEW.ACCION:='INSERT';
    ELSIF UPDATING THEN
    :NEW.ACCION:='UPDATE';
    END IF;
END;
/
-- Accion FIDE_DIRECCION_CANTON_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_DIRECCION_CANTON_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_CANTON_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_DIRECCION_DISTRITO_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_DIRECCION_DISTRITO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_DIRECCION_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_DIRECCION_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_TELEFONO_CONTACTO_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_TELEFONO_CONTACTO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_TELEFONO_CONTACTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_TIPO_USUARIO_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_TIPO_USUARIO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_ESPECIALIDAD_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_ESPECIALIDAD_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESPECIALIDAD_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_USUARIOS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_USUARIOS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_MASCOTA_ESPECIE_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_MASCOTA_ESPECIE_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_MASCOTA_ESPECIE_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_MASCOTA_RAZA_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_MASCOTA_RAZA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_MASCOTA_RAZA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_MASCOTA_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_MASCOTA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_MASCOTA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_TIPO_EXAMEN_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_TIPO_EXAMEN_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_EXAMEN_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_EXAMENES_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_EXAMENES_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_EXAMENES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_CONSULTA_MOTIVO_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_CONSULTA_MOTIVO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_CONSULTA_MOTIVO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_CONSULTAS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_CONSULTAS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_CONSULTAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_FACTURACIONES_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_FACTURACIONES_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURACIONES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_PROVEEDORES_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_PROVEEDORES_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVEEDORES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_PRODUCTOS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_PRODUCTOS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_DETALLE_FACTURA_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_DETALLE_FACTURA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_ORDEN_PRODUCTOS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_ORDEN_PRODUCTOS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_ORDEN_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_ORDEN_COMPRA_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_ORDEN_COMPRA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_ORDEN_COMPRA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_TIPO_VIA_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_TIPO_VIA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_VIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_ROLES_CIRUGIA_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_ROLES_CIRUGIA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROLES_CIRUGIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_REGISTRO_CIRUGIAS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_REGISTRO_CIRUGIAS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_REGISTRO_CIRUGIAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_CIRUGIAS_MEDICAMENTOS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_CIRUGIAS_MEDICAMENTOS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_CIRUGIAS_MEDICAMENTOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_CIRUGIAS_PERSONAL_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_CIRUGIAS_PERSONAL_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_CIRUGIAS_PERSONAL_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_HISTORIALES_MEDICOS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_HISTORIALES_MEDICOS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_HISTORIALES_MEDICOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
-- Accion FIDE_PAGOS_PLANILLAS_TB
CREATE OR REPLACE TRIGGER ACCION_FIDE_PAGOS_PLANILLAS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_PAGOS_PLANILLAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
