--Creacion de trigger para reducir el stock de un producto cuando se venda
CREATE OR REPLACE TRIGGER REBAJAR_STOCK_PRODUCTO_TRG
BEFORE INSERT ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
DECLARE
    V_STOCK_ACTUAL NUMBER;
BEGIN
    SELECT STOCK 
    INTO V_STOCK_ACTUAL
    FROM FIDE_PRODUCTOS_TB
    WHERE ID_PRODUCTO_PK = :NEW.ID_PRODUCTO_FK;
    IF V_STOCK_ACTUAL < :NEW.CANTIDAD THEN
        DBMS_OUTPUT.PUT_LINE('Producto sin stock');
    ELSE
        UPDATE FIDE_PRODUCTOS_TB
        SET STOCK = STOCK - :NEW.CANTIDAD
        WHERE ID_PRODUCTO_PK = :NEW.ID_PRODUCTO_FK;
        DBMS_OUTPUT.PUT_LINE('STOCK ACTUALIZADO CORRECTAMENTE');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL PRODUCTO PARA REBAJAR EL STOCK');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR COMUNIQUESE CON TI ' || SQLERRM);
END;
/
--Creacion de trigger para aumentar el stock cuando se le compra a los proveedores
CREATE OR REPLACE TRIGGER AUMENTAR_STOCK_PRODUCTO_TRG
BEFORE INSERT ON FIDE_ORDEN_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    -- Aumentar el stock del producto según la cantidad ordenada
    UPDATE FIDE_PRODUCTOS_TB
    SET STOCK = STOCK + :NEW.ORDEN_PRODUCTO_CANTIDAD
    WHERE ID_PRODUCTO_PK = :NEW.ID_PRODUCTO_FK;

    DBMS_OUTPUT.PUT_LINE('STOCK ACTUALIZADO CORRECTAMENTE');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL PRODUCTO PARA ACTUALIZAR EL STOCK');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR COMUNIQUESE CON TI ' || SQLERRM);
END;
/
--Creacion de trigger para evitar vender un producto que no se encuentra en stock
CREATE OR REPLACE TRIGGER BLOQUEAR_PRODUCTO_INACTIVO_TRG
BEFORE INSERT ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
DECLARE
    V_ESTADO NUMBER;
BEGIN
    SELECT ID_ESTADO_FK 
    INTO V_ESTADO
    FROM FIDE_PRODUCTOS_TB
    WHERE ID_PRODUCTO_PK = :NEW.ID_PRODUCTO_FK;
    IF V_ESTADO = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No hay stock en este producto.');
        :NEW.ID_PRODUCTO_FK := NULL; -- Bloquea la inserción
    END IF;
END;
/

