-- CREACION VISTA DE FACTURA
CREATE OR REPLACE VIEW FACTURA_DETALLES_V AS
SELECT
    F.ID_FACTURA_PK AS FACTURA_ID,
    F.FACTURA_FECHA_EMISION AS FECHA_EMISION,
    F.FACTURA_MONTO_TOTAL AS MONTO_TOTAL,
    F.FACTURA_DESCUENTO AS DESCUENTO,
    F.FACTURA_IMPUESTOS AS IMPUESTOS,
    F.FACTURA_MONTO_FINAL AS MONTO_FINAL,
    DF.LINEA AS LINEA_DETALLE,
    P.PRODUCTO_NOMBRE AS PRODUCTO,
    DF.CANTIDAD AS CANTIDAD,
    DF.MONTO_UNITARIO AS PRECIO_UNITARIO,
    DF.TOTAL AS SUBTOTAL
FROM
    FIDE_FACTURACIONES_TB F
    JOIN FIDE_DETALLE_FACTURA_TB DF ON F.ID_FACTURA_PK = DF.ID_FACTURA_FK
    JOIN FIDE_PRODUCTOS_TB P ON DF.ID_PRODUCTO_FK = P.ID_PRODUCTO_PK
WHERE
    F.ID_ESTADO_FK = 1;
/
-- CREACION VISTA DE INFORMACION DE MASCOTAS
CREATE OR REPLACE VIEW MASCOTA_DETALLES_V AS
SELECT
    M.ID_MASCOTA_PK AS MASCOTA_ID,
    M.NOMBRE_MASCOTA AS NOMBRE,
    M.FECHA_NACIMIENTO AS FECHA_NACIMIENTO,
    M.GENERO AS GENERO,
    ME.NOMBRE_ESPECIE AS ESPECIE,
    MR.NOMBRE_RAZA AS RAZA,
    U.USUARIO_NOMBRE AS DUENNO,
    U.USUARIO_CORREO AS CORREO_DUENNO
FROM
    FIDE_MASCOTA_TB M
    JOIN FIDE_MASCOTA_ESPECIE_TB ME ON M.ID_MASCOTA_ESPECIE_FK = ME.ID_MASCOTA_ESPECIE_PK
    JOIN FIDE_MASCOTA_RAZA_TB MR ON M.ID_MASCOTA_RAZA_FK = MR.ID_MASCOTA_RAZA_PK
    JOIN FIDE_USUARIOS_TB U ON M.ID_USUARIO_FK = U.ID_USUARIO_PK
WHERE
    M.ID_ESTADO_FK = 1;
/
-- CREACION VISTA DE INFORMACION DE CLIENTES
CREATE OR REPLACE VIEW INFO_CLIENTE_V AS
SELECT
    U.ID_USUARIO_PK AS USUARIO_ID,
    U.USUARIO_NOMBRE AS NOMBRE,
    U.USUARIO_CORREO AS CORREO,
    U.USUARIO_IDENTIFICACION AS IDENTIFICACION,
    U.USUARIO_FECHA_REGISTRO AS FECHA_REGISTRO,
    D.DIRECCION_SENNAS AS DIRECCION,
    DP.NOMBRE_PROVINCIA AS PROVINCIA,
    DC.NOMBRE_CANTON AS CANTON,
    DD.NOMBRE_DISTRITO AS DISTRITO,
    TC.TELEFONO_CONTACTO AS TELEFONO
FROM
    FIDE_USUARIOS_TB U
    JOIN FIDE_DIRECCION_TB D ON U.ID_DIRECCION_FK = D.ID_DIRECCION_PK
    JOIN FIDE_DIRECCION_PROVINCIA_TB DP ON D.ID_DIRECCION_PROVINCIA_FK = DP.ID_DIRECCION_PROVINCIA_PK
    JOIN FIDE_DIRECCION_CANTON_TB DC ON D.ID_DIRECCION_CANTON_FK = DC.ID_DIRECCION_CANTON_PK
    JOIN FIDE_DIRECCION_DISTRITO_TB DD ON D.ID_DIRECCION_DISTRITO_FK = DD.ID_DIRECCION_DISTRITO_PK
    JOIN FIDE_TELEFONO_CONTACTO_TB TC ON U.ID_TELEFONO_CONTACTO_FK = TC.ID_TELEFONO_CONTACTO_PK
WHERE
    U.ID_ESTADO_FK = 1
    and 
    U.ID_TIPO_USUARIO_FK = 8;
    
/
-- CREACION VISTA DE HISTORIAL MEDICO DE MASCOTA
CREATE OR REPLACE VIEW HISTORIAL_MEDICO_V AS
SELECT
    HM.ID_HISTORIAL_MEDICO_PK AS HISTORIAL_ID,
    M.NOMBRE_MASCOTA AS MASCOTA,
    HM.HISTORIAL_FECHA_REGISTRO AS FECHA_REGISTRO,
    HM.HISTORIAL_DIAGNOSTICO AS DIAGNOSTICO,
    HM.HISTORIAL_TRATAMIENTO AS TRATAMIENTO,
    HM.HISTORIAL_NOTAS AS NOTAS,
    C.CONSULTA_FECHA AS FECHA_CONSULTA,
    CM.DESCRIPCION_MOTIVO AS MOTIVO_CONSULTA
FROM
    FIDE_HISTORIALES_MEDICOS_TB HM
    JOIN FIDE_MASCOTA_TB M ON HM.ID_MASCOTA_FK = M.ID_MASCOTA_PK
    JOIN FIDE_CONSULTAS_TB C ON HM.ID_CONSULTA_FK = C.ID_CONSULTA_PK
    JOIN FIDE_CONSULTA_MOTIVO_TB CM ON C.ID_CONSULTA_MOTIVO_FK = CM.ID_CONSULTA_MOTIVO_PK
WHERE
    HM.ID_ESTADO_FK = 1;
/
-- CREACION VISTA DE PRODUCTOS
CREATE OR REPLACE VIEW PRODUCTOS_DETALLES_V AS
SELECT
    P.ID_PRODUCTO_PK AS PRODUCTO_ID,
    P.PRODUCTO_NOMBRE AS NOMBRE,
    P.PRODUCTO_DESCRIPCION AS DESCRIPCION,
    P.PRODUCTO_PRECIO_UNITARIO AS PRECIO_UNITARIO,
    P.PRODUCTO_STOCK AS STOCK,
    PR.PROVEEDOR_NOMBRE AS PROVEEDOR,
    PR.PROVEEDOR_CORREO AS CORREO_PROVEEDOR,
    E.ESTADO_DESCRIPCION AS ESTADO
FROM
    FIDE_PRODUCTOS_TB P
    JOIN FIDE_PROVEEDORES_TB PR ON P.ID_PROVEEDOR_FK = PR.ID_PROVEEDOR_PK
    JOIN FIDE_ESTADO_TB E ON P.ID_ESTADO_FK = E.ID_ESTADO_PK
WHERE
    P.ID_ESTADO_FK = 1;

-- Vista para FIDE_ESTADO_TB
CREATE OR REPLACE VIEW FIDE_ESTADO_V AS
SELECT ID_ESTADO_PK, ESTADO_DESCRIPCION, CREATED_BY, CREATION_DATE, MODIFIED_BY, MODIFICATION_DATE, ACCION
FROM FIDE_ESTADO_TB;

-- Vista para FIDE_DIRECCION_PROVINCIA_TB
CREATE OR REPLACE VIEW FIDE_DIRECCION_PROVINCIA_V AS
SELECT ID_DIRECCION_PROVINCIA_PK, ID_ESTADO_FK, NOMBRE_PROVINCIA,
       CREATED_BY, CREATION_DATE, MODIFIED_BY, MODIFICATION_DATE, ACCION
FROM FIDE_DIRECCION_PROVINCIA_TB;

-- Vista para FIDE_DIRECCION_CANTON_TB
CREATE OR REPLACE VIEW FIDE_DIRECCION_CANTON_V AS
SELECT ID_DIRECCION_CANTON_PK, ID_ESTADO_FK, NOMBRE_CANTON,
       CREATED_BY, CREATION_DATE, MODIFIED_BY, MODIFICATION_DATE, ACCION
FROM FIDE_DIRECCION_CANTON_TB;

-- Vista para FIDE_DIRECCION_DISTRITO_TB
CREATE OR REPLACE VIEW FIDE_DIRECCION_DISTRITO_V AS
SELECT ID_DIRECCION_DISTRITO_PK, ID_ESTADO_FK, NOMBRE_DISTRITO,
       CREATED_BY, CREATION_DATE, MODIFIED_BY, MODIFICATION_DATE, ACCION
FROM FIDE_DIRECCION_DISTRITO_TB;

-- Vista para FIDE_DIRECCION_TB
CREATE OR REPLACE VIEW FIDE_DIRECCION_V AS
SELECT ID_DIRECCION_PK, ID_ESTADO_FK, ID_DIRECCION_PROVINCIA_FK,
       ID_DIRECCION_CANTON_FK, ID_DIRECCION_DISTRITO_FK,
       DIRECCION_SENNAS, CREATED_BY, CREATION_DATE,
       MODIFIED_BY, MODIFICATION_DATE, ACCION
FROM FIDE_DIRECCION_TB;



    